### ISSUE TITLE
Need an ID to create a document

### ISSUE THREAD

**Issue by alanbacon** [elastic/elasticsearch-py#516] opened 2017-01-10 18:25 UTC
in version 5 it appears that a document ID must be specified to create a document. If one is not specified the following error appears:

    TypeError: create() missing 1 required positional argument: 'id'

This is nonsensical. If I do not specify an ID elasticsearch should create one for me.

**Comment by HonzaKral** [comment] 2017-01-10 23:04
`create` API is nonsensical without the ID, if you don't have an ID you don't need the `create` API as you can just call `index` API.

`create` API exists only to **force** creation (and fail if document already exists).

Duplicate of #474

**Closed by HonzaKral** 2017-01-10 23:04 UTC

**Comment by alanbacon** [comment] 2017-01-11 10:31
Fair enough. Thanks

**Comment by tigerneil** [comment] 2017-08-02 10:07
so use `index` instead? 

BTW `create` can assign a customized id :)

**Comment by swethmandava** [comment] 2019-09-05 18:45
When I try to create with an id, I get:
`TypeError: create() got an unexpected keyword argument 'id'`
is it customizing the id by default then?

When I try to check if index exists, it requires an id: I'm not sure how I can check if index exists if I can't declare an id myself. Any thoughts?
