### ISSUE TITLE
helpers.scan not working (v7.0.3)

### ISSUE THREAD

**Issue by fernaper** [elastic/elasticsearch-py#1001] opened 2019-08-22 09:07 UTC
Hi I'm using Python 3.6.8
Since the last elasticsearch update I got an error with the `scan` method (with pyelasticsearch version `7.0.3`).

![image](https://user-images.githubusercontent.com/18369529/63501950-d8babd00-c4cc-11e9-8ef4-ff0f33a8fa89.png)

The problem is that it is not scrolling.

In the previous version `7.0.2` it works perfectly.

Thank you in advance :)

**Comment by HonzaKral** [comment] 2019-08-22 14:22
Hi, I have some trouble reproducing the issue, could you please check what version of elasticsearch server you are using?

thanks!

**Comment by fernaper** [comment] 2019-08-22 14:37
Hi, this is the version:
![image](https://user-images.githubusercontent.com/18369529/63523719-eedf7200-c4fa-11e9-91fd-7f7f7bab299b.png)

**Comment by HonzaKral** [comment] 2019-08-22 14:42
I still cannot replicate the issue as this works just fine for me:
```python
>>> from elasticsearch import Elasticsearch, helpers                                                                       
>>> es = Elasticsearch()                                                                                                   
>>> docs = list(helpers.scan(es, size=10, scroll='2m', query={'query': {'match_all': {}}}))                                
>>> len(docs)                                                                                                              
1046
```

Can you please share more information about the error? Ideally catch the exception and share the `.info` attribute and turn on logging for the `elasticsearch` logger.

thank you!

**Comment by fernaper** [comment] 2019-08-22 14:59
This is what I got:

```python
>>> try:
...     res = helpers.scan(es, size=10, scroll='2m',query={'query': {'match_all': {}}})
...     print('Res:', len(list(res)))
... except Exception as e:
...     print(e.info)
...
{'error': {'root_cause': [{'type': 'illegal_argument_exception', 'reason': 'Failed to parse request body'}], 'type': 'illegal_argument_exception', 'reason': 'Failed to parse request body', 'caused_by': {'type': 'json_parse_exception', 'reason': "Unrecognized token 'DnF1ZXJ5VGhlbkZldGNoGAAAAAAAAAQiFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAECxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABAwWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAQRFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAEDRY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABA4WODFuX095d2pRcW1O...': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@4a47c945; line: 1, column: 257]"}}, 'status': 400}
```

Sorry right now I can't turn on logging for the elasticsearch logger.

**Comment by HonzaKral** [comment] 2019-08-22 15:07
I still cannot eplicate this. The error message suggests that incorrect json is being passed to elasticsearch which should not be possible, specially not from the `scan` helper. Locally this exact code works for me.

Can you please share a complete example of the code, including the exact client initialization, and turn on the logging so we can see the exact message being passed through?

Sorry for the complications but there must be something we are not seeing...

**Comment by fernaper** [comment] 2019-08-22 15:42
I just created a `test.py` with this code:
```python
import elasticsearch
import platform

from elasticsearch import Elasticsearch, helpers

print('python version:', platform.python_version())
print('elasticsearch-py version:', elasticsearch.__version__)

es = Elasticsearch()
res = helpers.scan(es, size=10, scroll='2m',query={'query': {'match_all': {}}})

try:
    print('Length:', len(list(res)))
except Exception as e:
    print('Exception:', e.info)
```

And this is the `output` that I got:

```
python version: 3.6.8
elasticsearch-py version: (7, 0, 3)
Exception: {'error': {'root_cause': [{'type': 'illegal_argument_exception', 'reason': 'Failed to parse request body'}], 'type': 'illegal_argument_exception', 'reason': 'Failed to parse request body', 'caused_by': {'type': 'json_parse_exception', 'reason': "Unrecognized token 'DnF1ZXJ5VGhlbkZldGNoGAAAAAAAAAS1Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAEnxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABKAWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAASeFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAEoRY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABKIWODFuX095d2pRcW1O...': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@731df8ae; line: 1, column: 257]"}}, 'status': 400}
```

Also, can you send me a guide on how to change the logging?
So I can do it as soon as possible.

I haven't changed any default path, what logging file do you want to see?
`/var/log/elasticsearch/elastichsearch.log`?

**Comment by HonzaKral** [comment] 2019-08-22 15:46
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```
should do the trick, at the top of your file. You should then see the log on stdout. I am interested in lines starting with `DEBUG:elasticsearch:>`

thank you!

**Comment by fernaper** [comment] 2019-08-22 15:58
I just did it, and this is the response:

```
python version: 3.6.8
elasticsearch-py version: (7, 0, 3)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9200
DEBUG:urllib3.connectionpool:http://localhost:9200 "GET /_all/_search?scroll=2m&size=10 HTTP/1.1" 200 4221
INFO:elasticsearch:GET http://localhost:9200/_all/_search?scroll=2m&size=10 [status:200 request:0.006s]
DEBUG:elasticsearch:> {"query":{"match_all":{}},"sort":"_doc"}
DEBUG:elasticsearch:< {"_scroll_id":"DnF1ZXJ5VGhlbkZldGNoGAAAAAAAAAUwFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLhY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUIWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAVFFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTEWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAUyFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFMxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTUWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU0Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFNxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTYWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU_Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFOBY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTkWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU7Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFOhY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUMWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU8Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFPRY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABT4WODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAVEFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFQBY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUEWODFuX095d2pRcW1Od1VmUGNteGFCQQ==","took":2,"timed_out":false,"_shards":{"total":24,"successful":24,"skipped":0,"failed":0},"hits":{"total":{"value":13595081,"relation":"eq"},"max_score":null,"hits":[<10 first hits there>]}}
DEBUG:urllib3.connectionpool:http://localhost:9200 "GET /_search/scroll?scroll=2m HTTP/1.1" 400 672
WARNING:elasticsearch:GET http://localhost:9200/_search/scroll?scroll=2m [status:400 request:0.001s]
DEBUG:elasticsearch:> DnF1ZXJ5VGhlbkZldGNoGAAAAAAAAAUwFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLhY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUIWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAVFFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTEWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAUyFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFMxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTUWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU0Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFNxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTYWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU_Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFOBY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTkWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU7Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFOhY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUMWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU8Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFPRY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABT4WODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAVEFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFQBY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUEWODFuX095d2pRcW1Od1VmUGNteGFCQQ==
DEBUG:elasticsearch:< {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse request body"}],"type":"illegal_argument_exception","reason":"Failed to parse request body","caused_by":{"type":"json_parse_exception","reason":"Unrecognized token 'DnF1ZXJ5VGhlbkZldGNoGAAAAAAAAAUwFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLhY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUIWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAVFFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTEWODFuX095d2pRcW1O...': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@414b042a; line: 1, column: 257]"}},"status":400}
DEBUG:urllib3.connectionpool:http://localhost:9200 "DELETE /_search/scroll HTTP/1.1" 200 33
INFO:elasticsearch:DELETE http://localhost:9200/_search/scroll [status:200 request:0.001s]
DEBUG:elasticsearch:> {"scroll_id":["DnF1ZXJ5VGhlbkZldGNoGAAAAAAAAAUwFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLhY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUIWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAVFFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTEWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAUyFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFMxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTUWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU0Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFNxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTYWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU_Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFOBY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTkWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU7Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFOhY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUMWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAU8Fjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFPRY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABT4WODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAVEFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFQBY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUEWODFuX095d2pRcW1Od1VmUGNteGFCQQ=="]}
DEBUG:elasticsearch:< {"succeeded":true,"num_freed":24}
Exception: {'error': {'root_cause': [{'type': 'illegal_argument_exception', 'reason': 'Failed to parse request body'}], 'type': 'illegal_argument_exception', 'reason': 'Failed to parse request body', 'caused_by': {'type': 'json_parse_exception', 'reason': "Unrecognized token 'DnF1ZXJ5VGhlbkZldGNoGAAAAAAAAAUwFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLhY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABUIWODFuX095d2pRcW1Od1VmUGNteGFCQQAAAAAAAAVFFjgxbl9PeXdqUXFtTndVZlBjbXhhQkEAAAAAAAAFLxY4MW5fT3l3alFxbU53VWZQY214YUJBAAAAAAAABTEWODFuX095d2pRcW1O...': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@414b042a; line: 1, column: 257]"}}, 'status': 400}
```

NOTE: I removed the 10 first hits from the output

**Comment by HonzaKral** [comment] 2019-08-22 16:12
Thank you for your patience, I realized the problem is that you are using an old version of the code which got accidentally released in the `wheel` version of package. I just release `7.0.4` which corrects the mistake. My apologies!

**Closed by HonzaKral** 2019-08-22 16:12 UTC
