### ISSUE TITLE
Compatibility with grequests/gevent?

### ISSUE THREAD

**Issue by hermanocabral** [elastic/elasticsearch-py#150] opened 2014-11-14 23:26 UTC
Howdy,

Is this client compatible with grequests? I'm not looking for official support, just want to know if this has been tested or used by someone.

Thanks

**Comment by msukmanowsky** [comment] 2015-05-22 19:10
We're also looking at this after discovering that multisearch doesn't seem to respect timeouts that we pass and for long running aggregations, that can be a big issue if the query takes many seconds to run and bogs down. Since this is probably an issue for others, perhaps it's something we can get a proper example of using maybe gevent or plain threading? What do you think @HonzaKral?

**Comment by HonzaKral** [comment] 2015-05-22 19:12
How are you specifying the timeout?

**Comment by msukmanowsky** [comment] 2015-05-22 19:12
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/elasticsearch/q-JVMOCaC0M. All of those methods fail.

**Comment by HonzaKral** [comment] 2015-05-22 19:16
Currently there is no way to make an operation timeout inside elasticsearch. The `_msearch` API doesn't accept `timeout` parameter.

Most you can do is specify the timeout on the client, which is done either by globally setting the `timeout` parameter on the client itself (`Elasticsearch(timeout=12)`) in seconds or by passing in `request_timeout` during the API call.

See http://elasticsearch-py.readthedocs.org/en/master/api.html#timeout

**Comment by msukmanowsky** [comment] 2015-05-22 19:19
Right, but if I understand, specifying that simply means the client will wait for a max of `timeout` seconds before deciding to raise an error. ES will still happily continue chewing on the query.

The ES timeout is far more important for us here because long running queries can swamp an ES node unless they're killed after some amount of time allowing other queries to run.

Hence the interest in implementing a client-side `msearch` until ES accepts timeout for `_msearch`.

**Comment by msukmanowsky** [comment] 2015-05-22 19:24
Feature request added to ES https://github.com/elastic/elasticsearch/issues/11310

**Comment by msukmanowsky** [comment] 2015-05-22 19:33
Maybe this is a moot point considering https://www.elastic.co/guide/en/elasticsearch/guide/current/empty-search.html#_timeout

> Use the time-out because it is important to your SLA, not because you want to abort the execution of long-running queries.

**Comment by HonzaKral** [comment] 2015-05-22 20:35
Yeah, unfortunately there is no clean way to short circuit execution of a query so there is no way to guarantee execution of a search will stop and not burden the cluster.

**Comment by HonzaKral** [comment] 2015-06-15 23:11
Closing this issue since the original question has been answered.

**Closed by HonzaKral** 2015-06-15 23:11 UTC
Labels: question

**Comment by feifangit** [comment] 2016-01-09 03:26
well, I encountered the conflict issue. API calls to elasticsearch just hang there.
It's actually caused by the `urllib3`. I fixed by specify `connection_class` to `RequestHttpConnection`.
