### ISSUE TITLE
indices.put_template not accepting the parametter data_stream = {}

### ISSUE THREAD

**Issue by nubolio** [elastic/elasticsearch-py#2240] opened 2023-07-03 16:14 UTC
Hello,

when I try to create a index template I cannot find the way to pass the parameter data_stream as it is 
used for example here: https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-a-data-stream.html#create-index-template

I cannot find the way to pass that using this package neither the composed_of.

Any ideas? Thanks.

**Comment by pquentin** [comment] 2023-09-04 11:49
Hello! As @honzakral mentioned, you need to use https://elasticsearch-py.readthedocs.io/en/v8.9.0/api.html#elasticsearch.client.IndicesClient.put_index_template which does include `composed_of` and `data_stream`. I'm going to close this issue as it's not a bug in the client, but feel free to ask more questions in the [language clients section of the forums](https://discuss.elastic.co/tag/language-clients).

**Closed by pquentin** 2023-09-04 11:49 UTC
