### ISSUE TITLE
[question/bug] Async usage with Django 3.1+ 

### ISSUE THREAD

**Issue by vitalik** [elastic/elasticsearch-py#1303] opened 2020-06-29 23:22 UTC
**Elasticsearch version**: 7.8

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7.8.0

Django 3.1 (currently in beta) comes with async views support

Having an issue when use AsyncElasticsearch object:

```
# 1
pip insntall Django==3.1b1 

# 2
django-admin startproject myproject

# 3 in settings.py change WSGI_APPLICATION to 
ASGI_APPLICATION = 'myproject.asgi.application'

# 4 in urls.py

from django.urls import path
from django.http import JsonResponse
from elasticsearch import AsyncElasticsearch

es = AsyncElasticsearch()

async def search(request):
    resp = await es.search(
        index="documents", body={"query": {"match_all": {}}}, size=20
    )
    return JsonResponse(resp)


urlpatterns = [
    path("search/", search),
]

# 5
./manage.py runserver

```

this gives exception when trying to use it (on 2nd call to web /search )

```
Traceback (most recent call last):
  File "lib/python3.8/site-packages/elasticsearch/_async/http_aiohttp.py", line 228, in perform_request
    async with self.session.request(
  File "lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "lib/python3.8/site-packages/aiohttp/client.py", line 405, in _request
    handle = tm.start()
  File "lib/python3.8/site-packages/aiohttp/helpers.py", line 532, in start
    return self._loop.call_at(at, self.__call__)
  File "/lib/python3.8/asyncio/base_events.py", line 698, in call_at
    self._check_closed()
  File "/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

...

  File "lib/python3.8/site-packages/elasticsearch/_async/http_aiohttp.py", line 255, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(Event loop is closed) caused by: RuntimeError(Event loop is closed

```

moving `es` object initialisation to view seems solve it, but it will create elastic client on every request...

**Comment by sethmlarson** [comment] 2020-06-30 00:11
Hmm, I tested the client in global scope against FastAPI and Starlette without issue, I'll try async Django and see why this is occurring.

My first thought is that Django is using a new event loop per request which would be interesting.

**Comment by sethmlarson** [comment] 2020-06-30 00:51
@vitalik After following your excellent steps (thank you very much!) I was able to reproduce the issue and see that my first instinct is unfortunately correct and that Django (when run with `manage.py runserver` specifically) hands every async view a new event loop and closes the previous event loop. This means that any libraries that do event loop detection at time of use (like this library, HTTPX, Hip, etc) will not work by default.

- It looks like there is a ticket on Django's tracker that has been accepted to support ASGI mode for `runserver`: https://code.djangoproject.com/ticket/31626. Hopefully that issue is resolved soon, will comment there pointing to your report here.
- Also as a work-around you can use any ASGI handler like [Daphne](https://github.com/django/daphne), [Uvicorn](https://www.uvicorn.org/), or [Hypercorn](https://pgjones.gitlab.io/hypercorn/) to mitigate this issue. They should all work properly and only use one event loop.

As far as things we can do I can add an entry to the async FAQ that mentions this issue and a recommended work-around but will close this issue as not-a-bug.
Again thanks for reporting this and for trying out async support! :)

**Closed by sethmlarson** 2020-06-30 00:51 UTC

**Comment by vitalik** [comment] 2020-06-30 06:51
@sethmlarson thanks for update
As a workaround... - how safe it is to create new instance of AsyncElasticsearch on every request (in search function view) ?

**Comment by sethmlarson** [comment] 2020-06-30 13:42
@vitalik It's totally safe to do so but it will incur harsh performance penalties since you won't be pooling connections. Maybe you can check out Django channels which supports ASGI runserver? Was mentioned in the Django issue above too.

**Comment by vitalik** [comment] 2020-06-30 13:59
@sethmlarson do you think  it makes sense to add some option like:

```
es = AsyncElasticsearch(enable_pooling=False)
```
specifically for Django:
```
es = AsyncElasticsearch(enable_pooling=not settings.DEBUG)
```

**Comment by sethmlarson** [comment] 2020-06-30 14:41
I don't think so, that would be working around a defect on the Django side and would have the same behavior as instantiating a new `AsyncElasticsearch` instance per call.

**Comment by Andrew-Chen-Wang** [comment] 2020-07-17 20:56
@vitalik The thing about this issue is that async with Django is far from being mature. If you were to `runserver` async, you should be using Uvicorn (with watchgod) or something similar with reload turned on. You can visit [cookiecutter-django](https://github.com/pydanny/cookiecutter-django) where we implemented a method for native websockets for Django; you can check the compose start files for how we run an async server locally and in production. That's pretty much your only option for now.

I think only Andrew Godwin is really pushing for native async support. Besides that, the one thing holding back much development is the lack of async database support; you'll have to wait until we develop [psycopg3](https://github.com/psycopg/psycopg3) for some more development of async Django.
