### ISSUE TITLE
UnsupportedProductError is harmful to those using older versions of Elasticsearch server

### ISSUE THREAD

**Issue by codeocelot** [elastic/elasticsearch-py#1734] opened 2021-09-23 04:50 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):

5.4.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 

7.14.0

Please make sure the major version matches the Elasticsearch server you are running.

> Yeah. Noted.  Saying you ought not to use elasticsearch-py 7 with older versions of elasticsearch server; and artificially hobbling your own product to pressure Amazon are vastly different things.

**Description of the problem including expected versus actual behavior**:

As it says on the tin, the `UnsupportedProductError` exception thrown in [transport.pyL433-L438](https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/transport.py#L433-L438) in response to a missing `X-Elasticsearch-Product` header is an unnecessarily hostile behaviour for users using a non-current version of Elasticsearch.  Effectively, you're treating users that can't or won't upgrade to Elasticsearch7 as second class citizens.  Yes, I know there's a version mis-match, and no, I don't feel that's a reasonable excuse to justify adding such a ridiculously developer-hostile 'feature' into this library.

I do understand the business need to be competitive, but at the very least, can you try implementing these things in a manner that doesn't displace long-standing users of your software, nor is so trivially easy to by bypass?  You aren't preventing the committed from using this project with OpenSearch, only new-comers to your ecosystem and python in general.  Anyone with a passing familiarity with this codebase should know that the Elasticsearch client class itself takes a Transport arg in it's constructor.  [aioelasticsearch](https://github.com/aio-libs/aioelasticsearch/blob/master/aioelasticsearch/__init__.py#L16) and others have been doing this for years.

The point is, if you're going to make an active effort to harm your userbase to spite your competitors, and least do it in a way that isn't 

a) Harmful to bona fide users of legitimate deployments of Elasticsearch
b) Trivial to bypass

Otherwise, you're no better than Steve Ballmer era Microsoft.

**Steps to reproduce**:

Make literally any request, and the artificial stumbling block inserted into [transport.py](https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/transport.py#L433-L438) throws an exception.

```py
# 'X-Elastic-Product: Elasticsearch' should be on every response
if headers_response.get("x-elastic-product", "") != "Elasticsearch":
    raise UnsupportedProductError(
        "The client noticed that the server is not Elasticsearch "
        "and we do not support this unknown product"
    )
```

**Comment by sethmlarson** [comment] 2021-09-23 12:36
Our clients are forward compatible, so if you're connecting to an Elasticsearch 5.x server you should use a 5.x client. You can either pin to `5.x` or to `<7.14`. Our recommended upgrade order is server first then clients.

Closing as duplicate of https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883587433

**Closed by sethmlarson** 2021-09-23 12:36 UTC
