### ISSUE TITLE
delete request_timeout args error 

### ISSUE THREAD

**Issue by mapengfei2016** [elastic/elasticsearch-py#1035] opened 2019-10-09 11:25 UTC
elasticsearch-7.2 :
I before use elasticsearch-5.6 version use the .indices.delete function, use request_timeout args because delete often timeout, now I update to 7.2 version ,this args can't use it , always report this error:   "TypeError: a float is required" , 
try trace source code, find this function will change int or float to string type , i find thie code from 5.0 never change ,but not error
so this is bug or design in this way:
https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/utils.py#L12

if not bug ,how do I use it? 
thanks!

**Comment by HonzaKral** [comment] 2019-10-29 14:23
That line does not affect `request_timeout` as `_escape` is only called for known params of the API call: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/utils.py#L78

Can you please share the code that is causing the error for you?
Thank you!

**Comment by HonzaKral** [comment] 2020-01-02 22:47
Closing this as this was caused by an issue fixed by https://github.com/elastic/elasticsearch-py/pull/1051

**Closed by HonzaKral** 2020-01-02 22:47 UTC
