### ISSUE TITLE
TransportError exception throws TypeError on HTTP 400 

### ISSUE THREAD

**Issue by starenka** [elastic/elasticsearch-py#536] opened 2017-02-10 14:54 UTC
```

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 289, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/django/views/debug.py", line 84, in technical_500_response
    html = reporter.get_traceback_html()
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/django/views/debug.py", line 316, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/django/views/debug.py", line 308, in get_traceback_data
    c['exception_value'] = smart_text(self.exc_value, errors='replace')
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/django/utils/encoding.py", line 42, in smart_text
    return force_text(s, encoding, strings_only, errors)
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/data/.envs/xxx/local/lib/python2.7/site-packages/elasticsearch/exceptions.py", line 57, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers
```

It seems sometimes like in certain situations (sorry, can't help you) `self.info['error']` is not a `dict` as expected but `unicode/str`: 

```
ipdb> type(self.info['error'])
<type 'unicode'>
ipdb> self.info
{u'status': 400, u'error': u'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][0]: SearchParseException[[xxx_companies_1485773934][0]: from[-1],size[-1]: Parse Failure [Fa
iled to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][1]: SearchParseExceptio
n[[xxx_companies_1485773934][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }{[jwhC
tTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][2]: SearchParseException[[xxx_companies_1485773934][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[mer
k_companies_1485773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][3]: SearchParseException[[xxx_companies_1485773934][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms"
: {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][4]: SearchParseException[[xxx_companies_1485773934][4]: from[-1],size[-1]: Parse Fa
ilure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }]'}                                                               
ipdb> self.args
(400, u'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][0]: SearchParseException[[xxx_companies_1485773934][0]: from[-1],size[-1]: Parse Failure [Failed to parse source 
[{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][1]: SearchParseException[[xxx_companies_148
5773934][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][m
erk_companies_1485773934][2]: SearchParseException[[xxx_companies_1485773934][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_148577393
4] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][3]: SearchParseException[[xxx_companies_1485773934][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-498078
20"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][4]: SearchParseException[[xxx_companies_1485773934][4]: from[-1],size[-1]: Parse Failure [Failed to pars
e source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }]', {u'status': 400, u'error': u'SearchPhaseExecutionException[Failed to execute phase [
query], all shards failed; shardFailures {[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][0]: SearchParseException[[xxx_companies_1485773934][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820
"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][1]: SearchParseException[[xxx_companies_1485773934][1]: from[-1],size[-1]: Parse Failure [Failed to parse 
source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][2]: SearchParseException[[xxx_compan
ies_1485773934][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9l
KDwQ][xxx_companies_1485773934][3]: SearchParseException[[xxx_companies_1485773934][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_14
85773934] bool query does not support [filter]]; }{[jwhCtTLvSNSdL4GP9lKDwQ][xxx_companies_1485773934][4]: SearchParseException[[xxx_companies_1485773934][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"bool": {"filter": [{"terms": {"_id": ["cz
-49807820"]}}]}}}]]]; nested: QueryParsingException[[xxx_companies_1485773934] bool query does not support [filter]]; }]'}
```

versions used:
elasticsearch==`2.4.1`
elasticsearch-dsl==`2.2.0`
python 2.7.13 deb

**Comment by HonzaKral** [comment] 2017-02-10 15:06
This looks like you have `elasticsearch-py` version `5.x` which is not compatible with elasticsearch `2.x`. Could you please verify?

Possible duplicate of #337

Thanks!

**Comment by starenka** [comment] 2017-02-10 17:56
Oh, silly me. Indeed the query was sent to 1.7 elastic w/ 2.x client. Sorry.

**Closed** 2017-02-12 15:20 UTC
