### ISSUE TITLE
How to configure to call with self-signed client certificate?

### ISSUE THREAD

**Issue by jthoni** [elastic/elasticsearch-py#588] opened 2017-05-15 17:05 UTC
I have an Elasticsearch cluster that I have been accessing from .Net web services via a ACL protected http endpoint.  I have spun up a new reverse proxy that uses SSL and requires a client certificate to forward the request on to the (now protected) Elasticsearch cluster.

I have this all working fine in .Net, but I have one service that I inherited that running Python.  I have not worked with Python much, and am struggling to figure out how to implement this.

I am using ES 2.3.2 and Python 3.2.

For .Net, I have the certificate installed on the hosting machine where the code pulls it directly from the store.  I used OpenSSL to convert my pfx to a pem, one with just the cert, and one with just the key.  I also exported by CA and created another pem that was the full chain.  I then create my client with:

	        client = Elasticsearch(hosts=[self.host], timeout=80, use_ssl=True, scheme="https", transport_schema="https", verify_certs=True, ca_certs=CA_file_path, client_cert=cert_file_path, client_key=key_file_path)

When I try to connect, it asks me for the password ("Enter PEM pass phrase:").  First, I need to figure out how to get around that as my service will be unattended.  I thought that having the key in the client_key would handle that.

```
GET https://[my server].cloudapp.net:443/ocv_int/_search?request_cache=true [status:N/A request:6.085s]
Traceback (most recent call last):
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\connectionpool.py", line 351, in _make_request
    self._validate_conn(conn)
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\connectionpool.py", line 814, in _validate_conn
    conn.connect()
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\jthoni\AppData\Local\Continuum\Anaconda3-2-3\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Users\jthoni\AppData\Local\Continuum\Anaconda3-2-3\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Users\jthoni\AppData\Local\Continuum\Anaconda3-2-3\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 94, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\connectionpool.py", line 604, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

  [1]: http://elasticsearch-py.readthedocs.io/en/2.3.0/api.html
```

How exactly do I need to configure this to work with my self-signed client certificate?

thanks,
~john

**Comment by jthoni** [comment] 2017-05-16 22:52
OK, I see that I can create my key file with RSA decrypted key in it.  I would prefer to be able to pull it directly from the Windows cert store, but I am not sure if that is doable.

So now, I have my cert in CA_file_path, my decrypted key in key_file_path and I created a bundle with the CA that I used to create my cert.  I am no longer prompted for password, but now I am getting failures in load_verify_locations of the context.

**Comment by jthoni** [comment] 2017-05-16 23:14
The error I get is:

```
Traceback (most recent call last):
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
ssl.SSLError: unknown error (_ssl.c:2738)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 94, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\connectionpool.py", line 351, in _make_request
    self._validate_conn(conn)
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\connectionpool.py", line 814, in _validate_conn
    conn.connect()
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\util\ssl_.py", line 297, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: unknown error (_ssl.c:2738)
GET https://[my URL]/ocv/_search?request_cache=true [status:N/A request:0.053s]
Traceback (most recent call last):
  File "E:\Source\Repos\OfficeCustomerVoice\UserExperience\OCVClusteringWebAPI\env3\lib\site-packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
ssl.SSLError: unknown error (_ssl.c:2738)
```

**Comment by fxdgear** [comment] 2017-10-25 17:43
@jthoni 

is your ca PEM formatted?

**Comment by fxdgear** [comment] 2017-10-25 17:45
closing cause dupe of https://github.com/elastic/elasticsearch-py/issues/591

**Closed by fxdgear** 2017-10-25 17:45 UTC
