### ISSUE TITLE
AttributeError: module 'certifi' has no attribute 'where'

### ISSUE THREAD

**Issue by jvalhondo** [elastic/elasticsearch-py#469] opened 2016-10-25 12:46 UTC
Hello,

I found the following issue when using elasticsearch==5.0.0

It seems to be a problem when setting up the connection due to the module 'certifi' because it has no attribute 'where'

Thanks for your help on beforehand.

```
/opt/conda/lib/python3.5/site-packages/elasticsearch/__init__.py in <module>()
     15     logger.addHandler(logging.NullHandler())
     16 
---> 17 from .client import Elasticsearch
     18 from .transport import Transport
     19 from .connection_pool import ConnectionPool, ConnectionSelector, \

/opt/conda/lib/python3.5/site-packages/elasticsearch/client/__init__.py in <module>()
      2 import logging
      3 
----> 4 from ..transport import Transport
      5 from ..exceptions import TransportError
      6 from ..compat import string_types, urlparse

/opt/conda/lib/python3.5/site-packages/elasticsearch/transport.py in <module>()
      2 from itertools import chain
      3 
----> 4 from .connection import Urllib3HttpConnection
      5 from .connection_pool import ConnectionPool, DummyConnectionPool
      6 from .serializer import JSONSerializer, Deserializer, DEFAULT_SERIALIZERS

/opt/conda/lib/python3.5/site-packages/elasticsearch/connection/__init__.py in <module>()
      1 from .base import Connection
      2 from .http_requests import RequestsHttpConnection
----> 3 from .http_urllib3 import Urllib3HttpConnection

/opt/conda/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py in <module>()
      8 try:
      9     import certifi
---> 10     CA_CERTS = certifi.where()
     11 except ImportError:
     12     pass

AttributeError: module 'certifi' has no attribute 'where'
```

**Comment by HonzaKral** [comment] 2016-10-25 13:31
Thanks for the report, unfortunately I cannot replicate it - `where` is the documented API of certifi: https://github.com/certifi/python-certifi#usage Could you please verify what version of certifi you have?

Thank you!

**Comment by jvalhondo** [comment] 2016-10-25 13:53
after manually installing 'certifi' latest version (2016.9.26) everything work fine.
`pip install -U certifi`

It seems that upgrading 'elasticsearch' module didn't install 'certifi' module, and I just had to install it manually. Then, don't know if 'certifi' should be a requirement.

To get it working it did:

```
pip install -U elasticsearch
pip install -U certifi
```

Thanks @HonzaKral, should I close this issue?

**Comment by HonzaKral** [comment] 2016-10-25 13:56
If you didn't have `certifi` installed then the import would have thrown an `ImportError` and the relevant code line would have been skipped. Something else happened there.

I will close the issue for now, if you, or anybody else of course, come up across this again please feel free to reopen with new information.

Thanks!

**Closed by HonzaKral** 2016-10-25 13:56 UTC

**Comment by ohadravid** [comment] 2016-11-08 15:07
Hi,

I encountered this as well.

For a minimal reproduction, run:
```bash
docker run -it jupyter/minimal-notebook /bin/bash
$ pip install elasticsearch
$ python -c "import elasticsearch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.5/site-packages/elasticsearch/__init__.py", line 17, in <module>
    from .client import Elasticsearch
  File "/opt/conda/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 4, in <module>
    from ..transport import Transport
  File "/opt/conda/lib/python3.5/site-packages/elasticsearch/transport.py", line 4, in <module>
    from .connection import Urllib3HttpConnection
  File "/opt/conda/lib/python3.5/site-packages/elasticsearch/connection/__init__.py", line 3, in <module>
    from .http_urllib3 import Urllib3HttpConnection
  File "/opt/conda/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 10, in <module>
    CA_CERTS = certifi.where()
AttributeError: module 'certifi' has no attribute 'where'
```

What happen is that `import certifi` give a weird `namespace`, which has nothing:
```py
>>> import certifi
>>> certifi
<module 'certifi' (namespace)>
>>> dir(certifi)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

I think you should just add `certifi` to your `install_requires` (or improve the check using `hasattr`).

For now I can use the workaround of `pip install -U certifi`, but it's annoying.

**Comment by jvalhondo** [comment] 2016-11-28 13:12
right @ohadravid I also keep facing the same issue and it seems to be due to the namespace.
I install 'certifi' with pip, and get rid of it, but it would be nice a more consistent approach.

**Comment by braunmagrin** [comment] 2017-01-24 14:40
I just had the same problem here. Installing certifi (using pip) fixed the problem as mentioned above.
I'm using both conda and pip. Maybe that's the problem, because before reinstalling certifi it wasn't being displayed in the `pip freeze` listing. Maybe the conda version is somehow broken.
I'll try and investigate it further later.

**Comment by valmunos** [comment] 2017-05-07 14:59
I'm also having this issue, except that the workaround is not working for me! Has anybody managed to resolve this?

**Comment by koursoh** [comment] 2019-06-03 14:51
@valmunos, did you find the solution for this issue? I have tried uinstalling and installing certifi using:

`sudo pip3 install -U certifi` , but I still have the same issue. Any way to fix this? 

Also I have checked in my Python3.6, inside /usr/local/lib/python3.6/dist-packages for certifi package installation, and it exists. Certifi = "2019.03.09".

**Comment by cowlinator** [comment] 2019-10-28 20:29
> What happen is that `import certifi` give a weird `namespace`, which has nothing:
> 
> ```python
> >>> import certifi
> >>> certifi
> <module 'certifi' (namespace)>
> >>> dir(certifi)
> ['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
> ```

I experienced this also.  My `Lib/site-packages` directory contained an empty `certifi` directory, which incorrectly allowed python to import the "module" without throwing a `ModuleNotFoundError`.

**Comment by dash-tobin** [comment] 2023-04-25 16:18
Just going to leave this here: https://pypi.org/project/certifi/

**Comment by senn** [comment] 2024-10-31 09:55
Same problem but installing `certifi` with pip does not solve it for me. It just states the requirement is already satisfied.

**Comment by pquentin** [comment] 2024-10-31 10:54
`certifi` is an install requirement of the Elasticsearch package since version 7.7, released more than four years ago at this point.

@senn This can happen when the place where you're installing the package to is not the same one as the place where you're running it from. This is why we suggest using `python -m pip install elasticsearch` to install the Elasticsearch client and then `python yourprogram.py` to run it. This makes sure that you're using the same Python. If that is not feasible, for example because you're running a web application, then make sure to use the same virtual environment.
