### ISSUE TITLE
Search Template: put_template error when used with json parameters

### ISSUE THREAD

**Issue by Wonay** [elastic/elasticsearch-py#639] opened 2017-08-24 20:07 UTC
Hi ! 
I am having an issue with ES method, `put_template`
```
with open(folder_path + '/' + filename) as template_file:
    template_content = template_file.read()
    res = es.put_template(template_name, template_content)
```

The file is a json which looks like that: 
```
{ "template": { "query": { "bool": {
    "filter": [  {  "term": { "something": "{{something}}" } } ],
    "must": [ {
        "nested": {
            "path": "nested_path",
                "query": {
                    "function_score": {
                       "script_score": {
                           "script": {
                               "inline": "HashMap input_vector = params.input_vector;",
                               "lang": "painless",
                               "params": {
                                   "input_vector": "{{#toJson}}input_vector{{/toJson}}"
                                }
                            }
                       }
                   }
              },
             "score_mode": "sum"
        } } ] }  },
        "size": 10
} }
```
And when I call it:

```
GET /[MY INDEX]/items/_search/template
{
  "id": "[MY SCRIPT NAME]",
  "params": {
    "something": 123456,
    "input_vector": {
      "123": "456",
      "46": "78"
    }
  }
}
```

The error I get is `"reason": "class_cast_exception: java.lang.String cannot be cast to java.util.HashMap"`

So I think the reason is because i do `"input_vector": "{{#toJson}}input_vector{{/toJson}}"`, in my search template. But if I do `"input_vector": {{#toJson}}input_vector{{/toJson}}` ( without the double quote ), I get: 
```
Traceback (most recent call last):
  
  File ".virtualenvs/prices/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File virtualenvs/prices/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 1497, in put_template
    'template', id), params=params, body=body)
  File ".virtualenvs/prices/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File ".virtualenvs/prices/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File ".virtualenvs/prices/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(500, u'unchecked_i_o_exception', u"unchecked_i_o_exception: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('{' (code 123)): was expecting double-quote to start field name\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@667ea5f6; line: 52, column: 67]")
```

**Comment by HonzaKral** [comment] 2017-08-24 20:15
The problem is that after `"{{#toJson}}input_vector{{/toJson}}"` renders it will still have the quotes around it so it will be a string, not a json object. If you want to use `toJson` you need to provide the template as a string, not as a json/dict objects. See the examples in the docs (0).

I will close this issue since it isn't related to the python client but to behavior of elasticsearch itself. If you want further help I would ask you to post your question on discuss.elastic.co so that we can keep the issues here on topic. Thank you!

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#_converting_parameters_to_json

**Closed by HonzaKral** 2017-08-24 20:15 UTC

**Comment by Wonay** [comment] 2017-08-24 20:24
well I asked it here because I don't know how to use the python API to pass my template as a string.

**Comment by HonzaKral** [comment] 2017-08-24 20:27
@Wonay if you just have the template code in the file, not the entire body do:
```
with open(folder_path + '/' + filename) as template_file:
    template_content = template_file.read()
    res = es.put_template(template_name, {'template': template_content})
```
That way it will properly serialize as a json containing a string in the `template` field.

Hope this helps

**Comment by Wonay** [comment] 2017-08-24 20:32
I just tried, it return this error: 
`elasticsearch.exceptions.RequestError: TransportError(400, u'parsing_exception', u'unexpected token [VALUE_STRING], expected [{]')`
my file look like that now: 
```
"query": { "bool": {
    "filter": [  {  "term": { "something": "{{something}}" } } ],
    "must": [ {
        "nested": {
            "path": "nested_path",
                "query": {
                    "function_score": {
                       "script_score": {
                           "script": {
                               "inline": "HashMap input_vector = params.input_vector;",
                               "lang": "painless",
                               "params": {
                                   "input_vector": "{{#toJson}}input_vector{{/toJson}}"
                                }
                            }
                       }
                   }
              },
             "score_mode": "sum"
        } } ] }  },
        "size": 10
```
and the python part:
```
template_content = template_file.read()
template_content = {"template": "%s" % template_content}
res = es.put_template(template_name, template_content)
```
i tried different version:
`template_content = {"template": template_content}`
`template_content = {"template": str(template_content) }`
`template_content = {"template": unicode(template_content) }`

but all return the same exception

**Comment by Wonay** [comment] 2017-08-24 21:03
okay it works ! Thanks for your help !

**Comment by mwangersjo** [comment] 2017-08-25 13:16
@Wonay @HonzaKral  I'm having the same problem but can't ge tit to work. I notice that @Wonay 's {{toJson}} is in quotes in the code above, which doesn't really render the correct query when you try to use it... When trying to pass in my template body as a string where the {{toJson}} tags are not within quotes, I get the `JsonParseException: Unexpected character ('{' (code 123)): was expecting double-quote to start field name\` error.. any ideas on how I get around this?

thanks

**Comment by Wonay** [comment] 2017-09-15 20:34
I did : 

``` 
              if template_extension == '.mustache':
                    template_content = {
                        "template": unicode(template_content)
                    }
```
