### ISSUE TITLE
UnsupportedProductError for 'oss' build flavor 

### ISSUE THREAD

**Issue by anushbmx** [elastic/elasticsearch-py#1665] opened 2021-08-04 16:51 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10 ( tested on 7.8, both cluster using 'oss' build flavour)

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7.14.0 

**Description of the problem including expected versus actual behavior**: UnsupportedProductError

**Steps to reproduce**: UnsupportedProductError is thrown on connecting to the ES server when `ProductChecker.check_product(info_headers, info_response)` gets executed.

I think the reasons for that is elasticsearch-py version 7.14.0 supports only 'build_flavor' = 'default' as per condition in here https://github.com/elastic/elasticsearch-py/blob/61e7a130979edd46af5ead00b03c25f71e0a2886/elasticsearch/transport.py#L655

which means using is 'oss' build triggers `UNSUPPORTED_DISTRIBUTION` error, is this intentional or an error ? 

reverting back to elasticsearch-py version 7.13.4 works fine.

**Comment by sethmlarson** [comment] 2021-08-04 17:03
Closing this as a duplicate of https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883319286.

**Closed by sethmlarson** 2021-08-04 17:03 UTC
