### ISSUE TITLE
update_by_query doesn't return source when `_source=True`

### ISSUE THREAD

**Issue by imedmar** [elastic/elasticsearch-py#783] opened 2018-05-06 16:32 UTC
It is [documented](https://elasticsearch-py.readthedocs.io/en/master/api.html?highlight=update_by_query) that

> _source – True or false to return the _source field or not, or a list of fields to return

But when I make the call `es.update_by_query(index=<index>, doc_type=<type>, body=query, size=1, _source=True)`, where `query` is something like:
```json
{
    "script": {
        "source": "ctx._source.likes += params.likes",
        "lang": "painless",
        "params": {
            "likes": 1
        }
    },
    "query": {
        "term": {
            "id": "1234"
        }
    }
}
```

I get the following response (note that `_source` is not returned):

```json
{
  "took": 10,
  "timed_out": False,
  "total": 1,
  "updated": 1,
  "deleted": 0,
  "batches": 1,
  "version_conflicts": 0,
  "noops": 0,
  "retries": {
    "bulk": 0,
    "search": 0
  },
  "throttled_millis": 0,
  "requests_per_second": -1,
  "throttled_until_millis": 0,
  "failures": [
    
  ]
}
```

Let me know if you need more info to reproduce this.

_This might also be related to issue #782_

**Comment by vandir** [comment] 2019-01-07 14:51
The problem is still present: the "_source" flag is ignored

**Comment by danielsnider** [comment] 2019-04-04 19:58
I have this issue as well! 😭

**Comment by lambdaq** [comment] 2019-11-27 10:35
same issue.

**Comment by ignacio-dl** [comment] 2020-05-08 20:54
How can I manage to get the fields I want without making another query if the _source param is ignored?

**Comment by sethmlarson** [comment] 2021-03-01 16:43
Closing this for the same reason in https://github.com/elastic/elasticsearch-py/issues/782, this is an Elasticsearch documentation issue and not an issue with specifically `elasticsearch-py`.

**Closed by sethmlarson** 2021-03-01 16:43 UTC
