### ISSUE TITLE
urllib3 > 1.10 breaks connection

### ISSUE THREAD

**Issue by katrielt** [elastic/elasticsearch-py#253] opened 2015-07-22 12:47 UTC
When using latest urllib3 (1.11 as of now), http connection breaks

AttributeError: 'module' object has no attribute 'HTTPMessage'
WARNING:elasticsearch:GET http:/server:443/es/index/_search [status:N/A request:13.243s]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 388, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/Library/Python/2.7/site-packages/urllib3/util/response.py", line 49, in assert_header_parsing
    if not isinstance(headers, httplib.HTTPMessage):
AttributeError: 'module' object has no attribute 'HTTPMessage'

Reverting back to urllib3==1.10.4 fixes the problem

setup.py specifies:
install_requires = [
    'urllib3>=1.8, <2.0',
]

Perhaps it should be changed to 
install_requires = [
    'urllib3>=1.8, <1.11',
]

until this is fixed.

**Comment by xcambar** [comment] 2015-07-22 14:12
Ha ha excellent!
I've spent my morning trying to fix this (not fluent in python yet) and then I see your issue+fix created one hour ago! 

Thank you very much @katrielt, I can confirm both the issue and fix.

**Comment by pquentin** [comment] 2015-07-24 09:46
We got bitten by this one too. Only affects ES 1.7, it seems.

**Comment by daviddyball** [comment] 2015-07-24 10:08
@pquentin we're running `elasticsearch==1.6.0` and `elasticsearch-dsl==0.0.5-dev0` and we get the same issues with `urllib3 >= 1.11`.

**Comment by HonzaKral** [comment] 2015-07-27 15:22
Thanks for the report. I am, however, having trouble replicating this issue.

I tried urllib3 1.11 with ES 1.5 and 1.7, python 2.7 and 3.4 and to no avail - tests pass and I can normally connect and talk to ES.

Could you please provide some code to replicate this issue?

Once we replicate this we also should open an issue with urllib3 since this is clearly a backwards incompatible change on their part which shouldn't happen.

**Comment by rrva** [comment] 2015-07-28 16:57
What about python 2.6?

**Comment by HonzaKral** [comment] 2015-07-28 17:03
2.6 works for me too with 1.11

**Comment by katrielt** [comment] 2015-07-29 07:37
When working in a clean virtualenv, I too was unable to re-produce.
This seems related to the presence of /Library/Python/2.7/site-packages/http/client.py on OSX., and the addition of the following line to urllib3==1.11 at /Library/Python/2.7/site-packages/urllib3/util/response.py:
```
try:
    import http.client as httplib
except ImportError:
    import httplib
```
This was added here - https://github.com/shazow/urllib3/commit/ffd95391951d1a2230eb43f57091181e11dc20d6
When changing that import to simply import httplib, it works with 1.11

http.client on my system reads:
```
from __future__ import absolute_import

from httplib import *
```

Seems like this is a urllib3 / OSX related issue... ?

**Comment by sigmavirus24** [comment] 2015-07-29 13:52
Do people have httpie installed?

**Comment by sigmavirus24** [comment] 2015-07-29 13:54
Nevermind, I checked the project and they use the namespace `httpie` not `http`. @katrielt what version of Python are you using?

**Comment by katrielt** [comment] 2015-07-29 13:55
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin

**Comment by sigmavirus24** [comment] 2015-07-29 13:56
>  This seems related to the presence of /Library/Python/2.7/site-packages/http/client.py on OSX., and the addition of the following line to urllib3==1.11 at /Library/Python/2.7/site-packages/urllib3/util/response.py:

I'm on OSX and I don't see this path at all. I have `/Library/Python/2.7/site-packages` but I don't have `http/` or `http/client.py`. That seems very ... odd.

**Comment by sigmavirus24** [comment] 2015-07-29 14:01
@xcambar @pquentin @daviddyball What versions of Python are you using and on what Operating Systems? This is necessary information to help determine how to fix this since this will likely affect users of urllib3 as well as elasticsearch-py.

**Comment by katrielt** [comment] 2015-07-29 14:08
http.client was introduced with Python 3, see the "Note" at the top of https://docs.python.org/2/library/httplib.html

I'm not sure how that module got into my Python 2.7 install. My guess the change to urllib3 was done for Python3 support.

**Comment by Koed00** [comment] 2015-07-29 14:11
Same troubles here:
* Python 2.7.9 
* Heroku Cedar-14 (Ubuntu 14.04 LTS)
* Bonsai ElasticSearch 1.5.2, Lucene 4.10.4

**Comment by sigmavirus24** [comment] 2015-07-29 15:23
@katrielt @Koed00 can you provide what other python packages you have installed. Something else is installing that `http/client.py` and it shouldn't be there.

**Comment by sigmavirus24** [comment] 2015-07-29 15:30
Do both of you have `pies` installed? if so that package is doing some gnarly stuff and should be avoided at all costs

**Comment by Koed00** [comment] 2015-07-29 15:32
@sigmavirus24 
```
arrow==0.6.0              # via django-q
beautifulsoup4==4.4.0
blessed==1.9.5            # via django-q
boto==2.38.0              # via django-require-s3
cffi==1.1.2               # via cryptography
cryptography==0.9.3       # via pyopenssl
django==1.8.3
docopt==0.4.0             # via mailchimp, mandrill
elasticsearch==1.6.0
elasticutils==0.10.3
enum34==1.0.4             # via cryptography
funcy==1.5                # via django-cacheops
future==0.15.0            # via django-q
hiredis==0.2.0
idna==2.0                 # via cryptography
ipaddress==1.0.14         # via cryptography
lxml==3.4.4               # via refreshbooks
mailchimp==2.0.9
mandrill==1.0.57
markdown==2.6.2
msgpack-python==0.4.6     # via django-redis
ndg-httpsclient==0.4.0
newrelic==2.52.0.40
oauthlib==1.0.1           # via requests-oauthlib
pillow==2.9.0             # via django-avatar
psycopg2==2.6.1
pyasn1==0.1.8
pycparser==2.14           # via cffi
pycrypto==2.6.1           # via yubiotp
pyopenssl==0.15.1
python-dateutil==2.4.2    # via arrow
python-openid==2.2.5      # via django-allauth
pytz==2015.4
pyyaml==3.11              # via django-rest-swagger
qrcode==5.1
redis==2.10.3
refreshbooks==2.0
requests-oauthlib==0.5.0  # via django-allauth
requests==2.7.0           # via django-allauth, django-whoshere, mailchimp, mandrill, requests-oauthlib
six==1.9.0                # via cryptography, django-appconf, django-cacheops, django-extensions, django-picklefield, elasticutils, pyopenssl, python-dateutil, qrcode, yubiotp
ua-parser==0.3.6          # via user-agents
urllib3==1.10.4           # via elasticsearch
user-agents==0.3.2
waitress==0.8.9
wcwidth==0.1.4            # via blessed
yubiotp==0.2.1
```
I left out all the django apps, but you can see what they depend on.

**Comment by sigmavirus24** [comment] 2015-07-29 17:29
@Koed00 any chance you can do `python -c 'import http.client; print(http.client)'` and then do `cat ...` of whatever that path is that the print shows you?

**Comment by Koed00** [comment] 2015-07-29 17:35
Points to ``http/client.py``:
```
from __future__ import absolute_import
import sys

assert sys.version_info[0] < 3

from httplib import *
from httplib import HTTPMessage

# These constants aren't included in __all__ in httplib.py:

from httplib import (HTTP_PORT,
                     HTTPS_PORT,

                     _CS_IDLE,
                     _CS_REQ_STARTED,
                     _CS_REQ_SENT,

                     CONTINUE,
                     SWITCHING_PROTOCOLS,
                     PROCESSING,

                     OK,
                     CREATED,
                     ACCEPTED,
                     NON_AUTHORITATIVE_INFORMATION,
                     NO_CONTENT,
                     RESET_CONTENT,
                     PARTIAL_CONTENT,
                     MULTI_STATUS,
                     IM_USED,

                     MULTIPLE_CHOICES,
                     MOVED_PERMANENTLY,
                     FOUND,
                     SEE_OTHER,
                     NOT_MODIFIED,
                     USE_PROXY,
                     TEMPORARY_REDIRECT,

                     BAD_REQUEST,
                     UNAUTHORIZED,
                     PAYMENT_REQUIRED,
                     FORBIDDEN,
                     NOT_FOUND,
                     METHOD_NOT_ALLOWED,
                     NOT_ACCEPTABLE,
                     PROXY_AUTHENTICATION_REQUIRED,
                     REQUEST_TIMEOUT,
                     CONFLICT,
                     GONE,
                     LENGTH_REQUIRED,
                     PRECONDITION_FAILED,
                     REQUEST_ENTITY_TOO_LARGE,
                     REQUEST_URI_TOO_LONG,
                     UNSUPPORTED_MEDIA_TYPE,
                     REQUESTED_RANGE_NOT_SATISFIABLE,
                     EXPECTATION_FAILED,
                     UNPROCESSABLE_ENTITY,
                     LOCKED,
                     FAILED_DEPENDENCY,
                     UPGRADE_REQUIRED,

                     INTERNAL_SERVER_ERROR,
                     NOT_IMPLEMENTED,
                     BAD_GATEWAY,
                     SERVICE_UNAVAILABLE,
                     GATEWAY_TIMEOUT,
                     HTTP_VERSION_NOT_SUPPORTED,
                     INSUFFICIENT_STORAGE,
                     NOT_EXTENDED,

                     MAXAMOUNT,
                    )

# These are not available on Python 2.6.x:
try:
    from httplib import LineTooLong, LineAndFileWrapper
except ImportError:
    pass

# These may not be available on all versions of Python 2.6.x or 2.7.x
try:
    from httplib import (
                         _MAXLINE,
                         _MAXHEADERS,
                         _is_legal_header_name,
                         _is_illegal_header_value,
                         _METHODS_EXPECTING_BODY
                        )
except ImportError:
    pass
```

**Comment by sigmavirus24** [comment] 2015-07-29 17:37
@Koed00 as in you have a module in your own project named `http` with a submodule of `client`? Or are you obscuring the full path for some other reason?

**Comment by Koed00** [comment] 2015-07-29 17:40
It just points to module` 'http.client'` from `'.virtualenvs/projectx/lib/python2.7/site-packages/http/client.pyc'>`

**Comment by sigmavirus24** [comment] 2015-07-29 17:52
So that's coming from https://github.com/PythonCharmers/python-future/blob/master/src/http/client.py which pulls `HTTPMessage` in explicitly and that works:

1. In a virtualenv install future, `pip install future`
2. Do the following:

```py
Python 2.7.10 (default, Jul  9 2015, 13:34:07)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import http.client as httplib
>>> httplib.HTTPMessage
<class httplib.HTTPMessage at 0x10e172f58>
```

So it's surprising you're seeing this @Koed00

**Comment by Koed00** [comment] 2015-07-29 18:02
@sigmavirus24  What's even more surprising is that I just did a deploy to staging with urllib3 1.11 and it now works without problems.

**Comment by sigmavirus24** [comment] 2015-07-29 18:05
`¯\_(ツ)_/¯`

So at least one problem here is `pies`. That's the library I found with code that @katrielt seems to be running into.

**Comment by Koed00** [comment] 2015-07-29 18:27
Excellent detective work @sigmavirus24 .Hmm I don't believe in magic , so I dug into my install history.
It seems the problem is `future==0.14.3`. When I downgrade to that version everything breaks like before with the same error messages. `future==0.15.0` only  came out 5 days ago and that fixes it.

Here's the ouput with future 0.14.3 installed in an empty virtualenv:

```
Python 2.7.8 (default, Jul  5 2015, 14:16:16) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import http.client as httplib
>>> httplib.HTTPMessage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'HTTPMessage'
```

**Comment by sigmavirus24** [comment] 2015-07-29 18:34
So here's the thing, these libraries are adding shims for Python 3 "compatibility" in Python 2. But what they do is break any other library (or application or whatever) on the system that is relying on Import Errors to import the right things. `pies` does a really awful job of shimming out `http.client` and `python-future` does a far more thorough (as of 0.15.0) job but may break *other* standard library modules for other things. That said, I don't think any of you are directly depending on these libraries so none of this is *your* fault. That said, you should be complaining to whomever is using those libraries about this. That said, we just merged [this pull request](https://github.com/shazow/urllib3/pull/688). This should avoid some of the problems. The biggest problem will be people who install `pies` or `python-future` on Python 3.x and break *everything* else. That's something the pull request in urllib3 will not fix for anyone.

**Comment by HonzaKral** [comment] 2015-08-24 23:47
Closing since this is an outside issue, thanks for the investigation @sigmavirus24 !

**Closed by HonzaKral** 2015-08-24 23:47 UTC

**Comment by sigmavirus24** [comment] 2015-08-25 01:17
Always happy to help @HonzaKral
