### ISSUE TITLE
Parameters on _cat commands out of date in docs

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch-py#982] opened 2019-07-18 19:50 UTC
In the `_cat/health` command (and maybe others), the `local` and `master_timeout` commands are no longer valid for the `_cat` API

```
GET _cat/health?master_timeout=1s&local=true
```

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "request [/_cat/health] contains unrecognized parameters: [local], [master_timeout]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "request [/_cat/health] contains unrecognized parameters: [local], [master_timeout]"
  },
  "status": 400
}
```

[The docs](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.client.CatClient.health) still list them as valid for this call. 

Interestingly, the same parameters are still valid under the `_cluster/health` command.

**Comment by jparkindeed** [comment] 2019-10-09 21:31
I can work on this one.

**Comment by viglia** [comment] 2019-12-13 12:24
Hi @PhaedrusTheGreek ,

Currently the most recent release of the `elasticsearch-py` client is V. `7.1`

Those two parameters were only removed in a later versions of ES (7.3).

I'm closing this ticket as this is not a bug but the expected behaviour.

The new client version that we'll release will be compliant with the rest spec of the same Elasticsearch version.

**Closed by viglia** 2019-12-13 12:24 UTC
Labels: Documentation, question
