### ISSUE TITLE
parallel_bulk not actually doing anything

### ISSUE THREAD

**Issue by k2xl** [elastic/elasticsearch-py#382] opened 2016-03-17 22:04 UTC
I'm trying to make reindexing big indices faster.
```
    for response in helpers.parallel_bulk(target_client, _change_doc_index(docs, target_index),
                                          chunk_size=10, thread_count=10, ** kwargs):
        print("response", response)
```
Nothing appears to happen... Switching to regular bulk things work fine...

Also, siginterrupt doesn't work with parallel bulk running

**Comment by HonzaKral** [comment] 2016-03-17 22:31
Can you please share the surrounding code how it looks like? My suspicion is that the client you are using doesn't have enough free connections - by default we limit the size of the connection pool within urllib3 to 10 (use the `maxsize` parameter to set it to higher value). I use parallel bulk and it has several tests so it should work in this case as well.

As a side note - setting `chunk_size` to 10 is probably not ideal since it will produce too many very small chunks - setting to higher number might get you better results (it is subject to many different factors so I recommend testing for the ideal value).

Thanks for the report about interrupt, I will look into it.

**Comment by k2xl** [comment] 2016-03-17 23:29
Hi HonzaKrai,

Thanks for the quick reply. The surrounding code is really just the rest of the code in helpers.py. I'm trying to make a parallel_reindex function since reindexing takes forever on large indices.

**Comment by HonzaKral** [comment] 2016-03-23 17:57
That is weird to me and I am afraid I cannot help you without further details. I cannot replicate your problem, `parallel_bulk` works for me and it works in every test environment I try it in (including travis-CI).

**Comment by mmontagna** [comment] 2016-03-24 18:42
I experienced similar when trying to use parallel_bulk() when running something like:

```
for response in helpers.parallel_bulk(es, iter, thread_count=2):
        print("response", response)
```

Switching to regular bulk() worked fine and was fast enough for me, but I just thought I'd
mention it. 

What other context can we give you?

**Comment by HonzaKral** [comment] 2016-03-25 16:05
I cannot replicate these issues so I have no idea what's going wrong. Did you try setting the `maxsize` parameter to higher than 10? Also if you could then enable logging and send any output to this issue.

Thanks!

**Comment by mmontagna** [comment] 2016-03-25 21:27
@HonzaKral I just tried to reproduce the problem and I wasn't able to; either I was doing something stupid, or perhaps the problem is intermittent. Anyway sorry for sending you on a wild goose chase!

**Comment by k2xl** [comment] 2016-03-30 20:35
Question - is there any reason why a parallel_reindex couldn't be built? That would simply underneath the hood use parallel_bulk instead of bulk?

**Comment by p1erce** [comment] 2016-04-28 10:05
Similar problem here.
`r = bulk(es, qs)` works. `r = parallel_bulk(es, qs)` does not do index.
Is it because of a custom analyzer?

**Comment by HonzaKral** [comment] 2016-04-28 10:09
`parallel_bulk` is a generator so you need to iterate over it to get to the results, see https://github.com/elastic/elasticsearch-py/issues/336

**Comment by p1erce** [comment] 2016-04-28 10:24
Hey, thanks. This solved my problem.
```
for r in parallel_bulk(es, qs):
    pass
```
I don't really need the return results. 
So I was wondering why `bulk(es, qs)` work and `parallel_bulk(es, qs)` does not at first.

**Comment by HonzaKral** [comment] 2016-08-16 18:42
Closing this issue since unable to replicate and tests are passing.

Please feel free to reopen with more information.

**Closed by HonzaKral** 2016-08-16 18:42 UTC

**Comment by rohanagarwal36** [comment] 2017-06-15 10:36
@HonzaKral I am experiencing the same issue. The updates the reflected sometimes and sometimes they are not. I am using parallel_bulk and I am also iterating over it. Also, I am using chunk size of 5000. Also, suppose I am updating 5 fields, it also happens sometimes that 4 fields are getting updated and one field is not. Not able to debug the problem.
```
def bulk_operation_helper(client, action, index, objects):
    actions = []
    index_connection_key = settings.HAYSTACK_CONNECTIONS.keys()[0]
    backend_class = libs_utils.import_obj(settings.HAYSTACK_CONNECTIONS[index_connection_key]['ENGINE']).backend
    backend = backend_class(index_connection_key, **settings.HAYSTACK_CONNECTIONS[index_connection_key])
    for obj in objects:
        data = obj[u'data']
        for key, value in data.iteritems():
            data[key] = backend._from_python(value)
        actions.append({
            u'_op_type': action,
            u'_index': index,
            u'_type': u'modelresult',
            u'_id': obj[u'id'],
            u'doc': data
        })
    # parallel bulk is a generator
    try:
        for item in parallel_bulk(client, actions, chunk_size=5000):
            pass
    except Exception:
        for item in parallel_bulk(client, actions, chunk_size=5000):
            pass
    client.indices.refresh(index)
```

**Comment by rakshify** [comment] 2018-02-17 12:59
Hi @HonzaKral , a similar problem is happening with me. Exact problem provided at the **end** of the post.
My index_mapping.json is:-
```
{
  "mappings": {
    "article": {
      "properties": {
        "created_at": {
          "type": "date"
        },
        "updated_at": {
          "type": "date"
        },
        "foreign_id": {
          "type": "keyword"
        }
     }
    },
    "segment": {
      "_parent": {
        "type": "article"
      },
      "properties": {
        "id": {
          "type": "keyword"
        },
        "created_at": {
          "type": "date"
        },
        "updated_at": {
          "type": "date"
        },
        "article_id": {
          "type": "keyword"
        }
      }
    }
  }
}
```

My action generator function is:-
```
def genereate_actions(data, index_name, doc_type):
    for i in range(len(data)):
        obj = {
            '_op_type': 'index',
            '_index': index_name,
             '_type': doc_type,
             '_source': data[i]
        }
        if doc_type == "article":
            obj['_id'] = str(data[i]["foreign_id"])
        elif doc_type == "segment":
            obj['_id'] = str(data[i]["id"])
            obj['_parent'] = str(data[i]["article_id"])

        yield obj
```


And finally below is my call to parallel_bulk:-
```
for success, info in parallel_bulk(client = client,\
                     actions = genereate_actions(article_data, self.index, "article"),\
                     thread_count = self.tc):
    if not success:
        print('Article indexing failed ', info)
print "ARTICLES INDEXED"

for success, info in parallel_bulk(client = client,\
                     actions = genereate_actions(segment_data, self.index, "segment"),\
                     thread_count = self.tc):
    if not success:
        print('Segment indexing failed ', info)
print "SEGMENTS INDEXED"
```


Exact problem with me is that Articles are getting indexed, but segments don't get indexed. It also doesn't go inside "if not success" part. It just prints `SEGMENTS INDEXED`, but 0 out of 899 segments get indexed.
