### ISSUE TITLE
es.explain on range query : inconsistent int size constraints

### ISSUE THREAD

**Issue by Alix-Martin** [elastic/elasticsearch-py#215] opened 2015-04-07 08:19 UTC
I'm trying to use explain on a range query through the python API :

(Pdb) es.explain("test8_ref05", doc_type="document", id="www.orange.fr/", body = """{"query": {"range": {"meta_description_ic": {"gte": 2147483648}}}}""")
{'_index': 'test8_ref05', '_type': 'document', '_id': 'www.orange.fr/', 'explanation': {'value': 1.0, 'details': [{'value': 1.0, 'description': 'boost'}, {'value': 1.0, 'description': 'queryNorm'}], 'description': 'ConstantScore(meta_description_ic:[-2147483648 TO *]), product of:'}, 'matched': True}

My lower bound, 2147483648 (=2^32), does not fit into a java int, and apparently gets cast to -2147483648

This does not happen if I use the ES API directly through Sense :

GET test/document/www.orange.fr/_explain
{"query": {"range": {"meta_description_ic": {"gte": 2147483648}}}}

{
"_index": "test",
"_type": "document",
"_id": "www.orange.fr",
"matched": false,
"explanation": {
"value": 0,
"description": "ConstantScore() doesn't match id 0"
}
}
which is what I expect, since my document has
"meta_description_ic": 1590728576

**Comment by HonzaKral** [comment] 2015-04-07 08:46
There are several odd things going on there. Could you please try the same in python using `'www.orange.fr'` as the id (without the trailing slash)? Since the python client escapes all characters in the url those are really different requests that you have in sense. To see exactly what's going on, consider turning on logging:

    import logging
    logging.basicConfig(level=logging.DEBUG )

Also you really don't need to send over json - you can just send a python dictionary and the library will serialise it properly.

**Comment by Alix-Martin** [comment] 2015-04-08 07:35
sorry for the confusion in the above message, I was using a different cluster/index with Marvel/Sense.

It looks like the problem is not in the python API but in ES itself, as I was able to reproduce it with curl.

Here are two queries with a single difference : the gte bound 
the first one behaves as expected, the doc doesn't match
in the second one, the gte bound is incremented by 1 to reach 2^32, and suddenly, the doc matches.


(trusty-idx-test1)ke@data001:~$ curl -XGET 'localhost:10948/xmt-test/document/forum.orange.fr%2Fmessages%2Findex%2F119945%2Fdiscriminations-monsieur-propre-monsieur-propre.html/_explain?pretty' -d '{"query": {"range": {"meta_description_ic": {"gte": 2147483647}}}}'
{
  "_index" : "xmt-test",
  "_type" : "document",
  "_id" : "forum.orange.fr/messages/index/119945/discriminations-monsieur-propre-monsieur-propre.html",
  "matched" : false,
  "explanation" : {
    "value" : 0.0,
    "description" : "ConstantScore() doesn't match id 147"
  }
}

(trusty-idx-test1)ke@data001:~$ curl -XGET 'localhost:10948/xmt-test/document/forum.orange.fr%2Fmessages%2Findex%2F119945%2Fdiscriminations-monsieur-propre-monsieur-propre.html/_explain?pretty' -d '{"query": {"range": {"meta_description_ic": {"gte": 2147483648}}}}'
{
  "_index" : "xmt-test",
  "_type" : "document",
  "_id" : "forum.orange.fr/messages/index/119945/discriminations-monsieur-propre-monsieur-propre.html",
  "matched" : true,
  "explanation" : {
    "value" : 1.0,
    "description" : "ConstantScore(meta_description_ic:[-2147483648 TO *]), product of:",
    "details" : [ {
      "value" : 1.0,
      "description" : "boost"
    }, {
      "value" : 1.0,
      "description" : "queryNorm"
    } ]
  }
}
I haven't been able to recreate it on a test cluster/index so far, but in any case, i's not the python API.

**Comment by HonzaKral** [comment] 2015-04-08 12:06
Thanks for the clarifications. I am closing this issue then.

If you found a problem with ES itself it would be great if you could post the curl reproduction as an issue to elasticsearch repo.

**Closed by HonzaKral** 2015-04-08 12:06 UTC
