### ISSUE TITLE
ILM Explain Parameter descriptions are swapped

### ISSUE THREAD

**Issue by TukeBean** [elastic/elasticsearch-py#2062] opened 2022-09-09 12:28 UTC
https://github.com/elastic/elasticsearch-py/blob/8bd20e94f9ad068cf6b0ef2acf9791150f790951/elasticsearch/_sync/client/ilm.py#L103

Descriptions for 'only_managed' and 'only_errors' have been swapped and are incorrect.

https://www.elastic.co/guide/en/elasticsearch/reference/8.2/ilm-explain-lifecycle.html

**Comment by sethmlarson** [comment] 2022-09-30 15:20
Thanks for opening this, this is duplicate of this issue: https://github.com/elastic/elasticsearch-specification/issues/1876 so I'll close this one and we can rely on the fix trickling down from the API specification.

**Closed by sethmlarson** 2022-09-30 15:20 UTC
