### ISSUE TITLE
Helper for retrieving all search results using the recommended search after method?

### ISSUE THREAD

**Issue by johann-petrak** [elastic/elasticsearch-py#1978] opened 2022-04-30 17:02 UTC
There is currently the "scan" helper, which is built on top of scroll, but since scroll is not recommended any more,
should this not be built on top of search after? Or could there be a helper to allow users to easily retrieve all search 
results in the proper order without having to deal with all those underlying implementation details of PIT, sort etc?

**Comment by ArnaudWald** [comment] 2022-09-26 08:01
Hey there, I took the existing code for the `scan` helper, and re-wrote it using the point in time API.
Here's a gist of the finished helper: [scan_pit.py](https://gist.github.com/ArnaudWald/583b3f6facd167328b15f4e610e84ba6)

Haven't tested it extensively, only on my own setup and a couple of searches and it works similarly to what `scan` did (which was my intention). 

Let me know if I can make a pull request to add this to the repo. Otherwise feel free to use it 😀

**Comment by sethmlarson** [comment] 2022-09-30 15:27
Going to close this as duplicate of https://github.com/elastic/elasticsearch-py/issues/2072, thanks for your suggestion!

**Closed by sethmlarson** 2022-09-30 15:27 UTC
Labels: feature request
