### ISSUE TITLE
update option "doc_as_upsert" needs text string "true" instead of boolean "True"

### ISSUE THREAD

**Issue by ersiko** [elastic/elasticsearch-py#440] opened 2016-08-23 21:00 UTC
Hi

Tried using "doc_as_upsert" in my updates. If the body of my request had a boolean value (ie "'doc_as_upsert': True") it didn't create new docs (it updated the existing ones, though). I needed to use 'true' in a text string (ie "'doc_as_upsert' : 'true'"), and then it created new documents. 

That means this call doesn't create new documents:

```
es.update(index="my_index", doc_type="my_doc_type", id=my_id, body={"doc":my_dict_update,'doc_as_upsert':True})
```

But this call does:

```
es.update(index="my_index", doc_type="my_doc_type", id=my_id, body={"doc":my_dict_update,'doc_as_upsert':'true'})
```

Maybe it's not a bug and it should work like that, as elasticsearch is expecting the string and not the boolean (maybe that should change in elasticsearch?). In that case, it would be a good idea to add a note to the documentation (I can try to help with that).

I'm using elasticsearch-py version 2.4 and elasticsearch version 2.3.4.

Thanks again!

**Comment by HonzaKral** [comment] 2016-10-07 15:11
I cannot replicate this with any elasticsearch version, it always works for me fine. The default serializer properly serializes boolen `True` to json's `true` which is accepted by elasticsearch and also used as an example in the docs.

Could you please provide a complete example of this issue so that I can try to recreate axactly what is happening to you?

Thanks!

**Comment by GlenRSmith** [comment] 2016-11-30 06:12
@ersiko Are you able to perform the reproduction @HonzaKral requested?

**Comment by HonzaKral** [comment] 2016-12-09 03:22
I am closing this as we are not able to replicate it. Please  feel free to reopen with additional information

**Closed by HonzaKral** 2016-12-09 03:22 UTC
