### ISSUE TITLE
Date format `yyyy-MM-dd HH:mm:ss.SSSSSSZ` doesn't work as expected?

### ISSUE THREAD

**Issue by zl700** [elastic/elasticsearch-py#1875] opened 2022-01-14 12:53 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):7.16.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.16.2

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

bulk insert errors when customizing date parser
parsing date "2015-11-14 18:10:06" with the format "yyyy-MM-dd HH:mm:ss" works,however parsing date "2015-11-14 18:10:06.924123+00" with format "yyyy-MM-dd HH:mm:ss.SSSSSSZ" doesn't

**Steps to reproduce**:

test.csv
model,date_created
bmw,2015-11-14 18:10:06.924123+00
ford,2015-11-14 20:50:15.954319+00

bug.py

```
from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk
import pandas as pd
import json

def generate_data(csv):
    df=pd.read_csv(csv)
    for i in df.index:
        j=json.loads(df.loc[i].to_json())
        j["date_created"] = str(j["date_created"])
        #the following works
        # j["date_created"] = str(j["date_created"]).split(".")[0][:19]
        j["_index"]="test"
        print(j)
        yield j



def create_index():
    es.indices.create(
        index="test",
        mappings={
            "properties": {
                "date_created": {
                    "type": "date",
                    "format": ["yyyy-MM-dd HH:mm:ss.SSSSSSZ"]
                    # the following works
                    # "format": ["yyyy-MM-dd HH:mm:ss"]
                },

            }
        }
    )


es=Elasticsearch()
create_index()
bulk(es, generate_data("test.csv"))


```

**Comment by sethmlarson** [comment] 2022-01-19 19:48
I'm not sure this is a problem specifically in the Python Elasticsearch client, can you try reproducing this with `curl` and seeing if both methods work and that one method doesn't work specifically with the client? That will likely help us narrow this issue down to where it's actually occurring (in Elasticsearch or in the client).

**Comment by sethmlarson** [comment] 2022-01-19 19:51
Also I'm wondering if the `+00` isn't a valid timezone specifier? Can you try `+00:00` or `Z`?

**Comment by zl700** [comment] 2022-01-20 01:29
That format works in both elasticsearch itself and pandas, it only doesn't work with this python client.
I'm new to collabarating with others, I can't even find out where the source code of parsing date is on this big github directory, Is it possible you point me where it is, I really want to learn.

**Comment by zl700** [comment] 2022-01-20 03:52
curl doesn't work too.

curl -XPOST "localhost:9200/test/_doc" -H 'Content-Type: application/json' -d'{"date_created": "2015-11-14 18:10:06.924123+00"}'
return the same error

but the dev tool in kibana works
POST /test/_doc
{
  "created_date":"2015-11-14 18:10:06.838319+00"
}

**Comment by sethmlarson** [comment] 2022-02-10 16:49
If curl doesn't work there's nothing the client can do here. I'm not sure if Kibana is doing something special, that seems strange? Maybe this can be raised as an Elasticsearch bug to accept these formats?

Since there's nothing the client can do I'm going to close this one.

**Closed by sethmlarson** 2022-02-10 16:49 UTC
