### ISSUE TITLE
Unexpected keyword argument 'pipeline' in es.index

### ISSUE THREAD

**Issue by Fenhanwang** [elastic/elasticsearch-py#918] opened 2019-03-26 13:25 UTC
The issue is that I can't use pipeline in the `es.index`. My elasticsearch-py is `6.3.1` and my elasticsearch from docker is '6.6.1'. I'm gonna paste the whole code later but here is the problematic line (in the save_pdf function )
```Python
self.es.index(index='test_index', doc_type='my_type', pipeline='attachment', body={'data': data}, id=file_name)
```

I plan to index some PDFs and I already test my Elasticsearch index by using `cURL`. It works. I also went through some open and closed issues but didn't find related topic.

Here is my whole
```Python
# -*- coding: utf-8 -*-
import scrapy
import datetime as dt
from datetime import datetime
from dateutil.parser import parse
import re
from scrapy_selenium import SeleniumRequest
import os
import base64
from elasticsearch import Elasticsearch


class NewyorkCitySpider(scrapy.Spider):
    name = 'newyork_city'
    allowed_domains = ['legistar.council.nyc.gov']
    start_urls = ['https://legistar.council.nyc.gov/Calendar.aspx/']
    es = Elasticsearch()

    def start_requests(self):
        for url in self.start_urls:
            yield SeleniumRequest(url=url, callback=self.parse)

    def parse(self, response):
        for link in response.xpath('//a[contains(.,"Agenda")]'):
            holder_name = ''.join(link.xpath('./ancestor::tr/td[1]/.//text()').getall()).strip()
            meeting_date = ''.join(link.xpath('./ancestor::tr/td[2]/.//text()').getall()).strip()
            holder_n_as_f = re.sub(r'[^A-Za-z]', '', holder_name.replace(' ', '')).lower()
            meeting_d_as_f = meeting_date.replace(' ', '')
            if holder_name is None:
                import ipdb; ipdb.set_trace()
            pdf_url = response.urljoin(link.xpath('./@href').get())
            file_name = re.sub(r'\/', '-', "{}_{}".format(holder_n_as_f, meeting_d_as_f))
            yield scrapy.Request(
                url=pdf_url,
                callback=self.save_pdf,
                meta={ 'file_name': file_name }
            )

            yield {
                'file_name': file_name,
                'url': pdf_url,
                'meeting_date': parse(meeting_date),
                'record_created_at': dt.datetime.now()
            }
    def save_pdf(self, response):
        os.chdir(r'/Users/msamac3/Documents/Statesearch/scrapy_backend/search_local_text/search_local_text')
        file_name = "pdf_{}.pdf".format(response.meta.get('file_name'))
        data = base64.b64encode(response.body).decode('ascii')

        result2 = self.es.index(index='test_index', doc_type='my_type', pipeline='attachment', body={'data': data}, id=file_name)
        import ipdb; ipdb.set_trace()

        file_name = re.sub(r'\/', '-', file_name) # "/" cannot be used here
        self.logger.info('Saving PDF %s', file_name)
        with open(file_name, 'wb') as f:
            # save the binary file
            # we can story to DB later
            f.write(response.body)
        print('nnno')
```

**Comment by Winterflower** [comment] 2019-06-25 12:18
Hey @Fenhanwang - I've been digging into your issue for a bit. I've confirmed from the v.6 documentation and code that `pipeline` should indeed be a supported keyword argument.
I suspect that your problem is stemming from the ordering of the arguments.

Have you tried adding `pipeline` argument at the very end, after all other arguments?
So instead of this

```
result2 = self.es.index(index='test_index', doc_type='my_type', pipeline='attachment', body={'data': data}, id=file_name)
```

You would have

```
result2 = self.es.index(index='test_index', doc_type='my_type',  body={'data': data}, id=file_name, pipeline='attachment')
```

I am still confirming this, but I suspect your trouble is due to the `query_params` decorator defined here https://github.com/elastic/elasticsearch-py/blob/6.x/elasticsearch6/client/utils.py#L62 and the way it interacts with the `Elasticsearch.index` function defined here https://github.com/elastic/elasticsearch-py/blob/6.x/elasticsearch6/client/__init__.py#L311.

I've tried to reduce your example to a sample dummy case that demonstrates what happens to a decorated function when a keyword argument is not passed after the rest of the arguments

```
from functools import wraps
  
def query_params(*es_args):
    """
    Decorator that pops all accepted parameters from method's kwargs and puts
    them in the params argument.
    """

    def _wrapper(func):
        @wraps(func)
        def _wrapped(*args, **kwargs):
            print('_wrapped args', args)
            print('_wrapped kwargs', kwargs)
            return func(*args, **kwargs)

        return _wrapped

    return _wrapper


@query_params('icecream')
def dummy_index(index, doctype, body, id=None, params=None):
    print(index)
    print(doctype)
    print(body)



def main():
    print('Calling dummy_index with pipeline kwarg last')
    dummy_index(index='hello', doctype='again', body='world', id='hello', pipeline='pipeline')
    print('Second time')
    dummy_index(index='hello', doctype='again', body='world', pipeline='pipeline', id='hello')



if __name__ == '__main__':
    main()
```

The first invocation of `dummy_index` works ('pipeline' is passed in last). The second invocation fails.

Here is the console output


```
 Calling dummy_index with pipeline kwarg last
_wrapped args ()
_wrapped kwargs {'index': 'hello', 'doctype': 'again', 'body': 'world', 'id': 'hello', 'pipeline': 'pipeline'}
Traceback (most recent call last):
  File "sample.py", line 38, in <module>
    main()
  File "sample.py", line 31, in main
    dummy_index(index='hello', doctype='again', body='world', id='hello', pipeline='pipeline')
  File "sample.py", line 14, in _wrapped
    return func(*args, **kwargs)
TypeError: dummy_index() got an unexpected keyword argument 'pipeline'
```

**Comment by sethmlarson** [comment] 2020-07-27 17:24
Closing this due to not being a defect in the library.

**Closed by sethmlarson** 2020-07-27 17:24 UTC

**Comment by Fenhanwang** [comment] 2020-07-27 18:51
> Hey @Fenhanwang - I've been digging into your issue for a bit. I've confirmed from the v.6 documentation and code that `pipeline` should indeed be a supported keyword argument.
> I suspect that your problem is stemming from the ordering of the arguments.
> 
> Have you tried adding `pipeline` argument at the very end, after all other arguments?
> So instead of this
> 
> ```
> result2 = self.es.index(index='test_index', doc_type='my_type', pipeline='attachment', body={'data': data}, id=file_name)
> ```
> 
> You would have
> 
> ```
> result2 = self.es.index(index='test_index', doc_type='my_type',  body={'data': data}, id=file_name, pipeline='attachment')
> ```
> 
> I am still confirming this, but I suspect your trouble is due to the `query_params` decorator defined here https://github.com/elastic/elasticsearch-py/blob/6.x/elasticsearch6/client/utils.py#L62 and the way it interacts with the `Elasticsearch.index` function defined here https://github.com/elastic/elasticsearch-py/blob/6.x/elasticsearch6/client/__init__.py#L311.
> 
> I've tried to reduce your example to a sample dummy case that demonstrates what happens to a decorated function when a keyword argument is not passed after the rest of the arguments
> 
> ```
> from functools import wraps
>   
> def query_params(*es_args):
>     """
>     Decorator that pops all accepted parameters from method's kwargs and puts
>     them in the params argument.
>     """
> 
>     def _wrapper(func):
>         @wraps(func)
>         def _wrapped(*args, **kwargs):
>             print('_wrapped args', args)
>             print('_wrapped kwargs', kwargs)
>             return func(*args, **kwargs)
> 
>         return _wrapped
> 
>     return _wrapper
> 
> 
> @query_params('icecream')
> def dummy_index(index, doctype, body, id=None, params=None):
>     print(index)
>     print(doctype)
>     print(body)
> 
> 
> 
> def main():
>     print('Calling dummy_index with pipeline kwarg last')
>     dummy_index(index='hello', doctype='again', body='world', id='hello', pipeline='pipeline')
>     print('Second time')
>     dummy_index(index='hello', doctype='again', body='world', pipeline='pipeline', id='hello')
> 
> 
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> The first invocation of `dummy_index` works ('pipeline' is passed in last). The second invocation fails.
> 
> Here is the console output
> 
> ```
>  Calling dummy_index with pipeline kwarg last
> _wrapped args ()
> _wrapped kwargs {'index': 'hello', 'doctype': 'again', 'body': 'world', 'id': 'hello', 'pipeline': 'pipeline'}
> Traceback (most recent call last):
>   File "sample.py", line 38, in <module>
>     main()
>   File "sample.py", line 31, in main
>     dummy_index(index='hello', doctype='again', body='world', id='hello', pipeline='pipeline')
>   File "sample.py", line 14, in _wrapped
>     return func(*args, **kwargs)
> TypeError: dummy_index() got an unexpected keyword argument 'pipeline'
> ```

Hey.Thanks for replying to me. I left the company. That's why I didn't reply to you.
But again, Thanks for the supporting and it's helpful for my further project.
