### ISSUE TITLE
Inconsistent behavior with body and index parameter order in the search method

### ISSUE THREAD

**Issue by ISMendys** [elastic/elasticsearch-py#2706] opened 2024-11-12 18:17 UTC
When using the search method in the Elasticsearch client library, I encountered an unexpected behavior where the order of the body, index, and size parameters affects the function's operation. Here are the details:

**Working code (as expected):**

```
es = get_elastic()
body = {"query": {"terms": {"_id": ids, "boost": 1.0}}}
try:
    response = es.search(index=index, body=body, size=len(ids))
except Exception as error:
    logging.error(error, exc_info=True)
    raise error
```
In this case, with index first, followed by body and size, the search works as expected.

**Code that throws an error:**

When the order of parameters is reversed, placing body before index, the search fails:

```
es = get_elastic()
body = {"query": {"terms": {"_id": ids, "boost": 1.0}}}
try:
    response = es.search(body=body, index=index, size=len(ids))
except Exception as error:
    logging.error(error, exc_info=True)
    raise error
```

Here, the search does not work, and the only relevant difference between these cases is the parameter order.

Code where the reversed order does not cause an error:

Even with body and index reversed, the search works when size is not used:

`response = es.search(body=body, index=index)`

**Summary of unexpected behavior**: This inconsistency appears specifically when adding the size parameter (elasticsearch version 8.15.0) while reversing the order of body and index. The expected behavior is for the search method to work regardless of parameter order as long as all provided parameters are valid.

**Comment by pquentin** [comment] 2024-11-13 05:01
Hello, and thank you for your clear report. I find the claim that the behavior changes based on the order of parameters really surprising. The point of forcing our users to use keyword arguments since elasticsearch-py 8.0 is to avoid this class of errors entirely. The client code itself does not care about the order, we let the Python interpreter handle it for us. Here's how `search()` is defined:

https://github.com/elastic/elasticsearch-py/blob/e67fed8d1ed9a2a74a5c8c42ccde5ac7ce0f3bdc/elasticsearch/_sync/client/__init__.py#L3752-L3848

* Are you certain that the *only* thing that changed is the order of parameters?
* How does the search fail when the order is different?
* Did you try printing them all in both cases to check they are the same?
* Is there a way for me to reproduce your issue?

**Comment by pquentin** [comment] 2024-11-15 04:38
I'm going to go ahead and close this, but I would still be happy to know if you fixed your problem or not. And I can always reopen if needed.

**Closed by pquentin** 2024-11-15 04:38 UTC
Labels: Area: Client, Category: Question
