### ISSUE TITLE
scan data from es may have memory leak

### ISSUE THREAD

**Issue by wx-ctrl-txc** [elastic/elasticsearch-py#1540] opened 2021-02-25 11:54 UTC
> I found memory leak when I've got data from elasticsearch. 

`import gc
import time
import psutil
import elasticsearch
from elasticsearch import Elasticsearch, helpers

print('elasticsearch version: ', elasticsearch.__version__)
print('start mem: {:.4f} gb'.format(psutil.virtual_memory().used / 1024 / 1024 / 1024))
es = Elasticsearch(hosts='192.168.83.222:9200')
query = {'query':{'term':{'ORG_NO':'3140201'}}}
repl = helpers.scan(client=es, query=query, index='hb_mp_info-3140201-2020.10.10', size=10000)
l = [ele for ele in repl]
del l
gc.collect()
time.sleep(5)
print('end mem: {:.4f} gb'.format(psutil.virtual_memory().used / 1024 / 1024 / 1024))`

Run the above code, we can see:
start mem: 6.3883 gb
end mem: 7.2465 gb
I feel that 0.86 gb memory ware leaking.

**Comment by danielmitterdorfer** [comment] 2021-03-02 07:01
Thanks for your interest in Elasticsearch and your report. You are measuring virtual memory usage for your entire system and not for the Elasticsearch process. The [psutil docs](https://psutil.readthedocs.io/en/latest/index.html#psutil.virtual_memory) are a bit vague on what this value actually represents but they do state that:

> [...] designed for informational purposes only. total - free does not necessarily match used.

Also increasing memory usage is not necessarily a sign of a memory leak, quite the contrary this is [by design](https://www.linuxatemyram.com/). 

A memory leak would manifest itself as increasing RSS (resident set size) of the Elasticsearch proccess, not virtual memory usage (see our blog for a [report of an investigation](https://www.elastic.co/blog/tracking-down-native-memory-leaks-in-elasticsearch) we did a couple of years ago). As Elasticsearch is a Java application, even RSS might increase while the application is running as the Java virtual machine (JVM) lazily allocates some native memory. However, unbounded growth would be problematic.

However, in this case here, the entire system's virtual memory usage very likely increases due to data being put into the page cache, thus I hope you don't mind that I close this issue.

**Closed by danielmitterdorfer** 2021-03-02 07:01 UTC

**Comment by kongklw** [comment] 2022-05-10 21:09
Have you solved this problem？my code also has memory leak .Look forward to your reply，thank you.

**Comment by Mihir-Gajera1** [comment] 2022-11-08 23:01
Having the same issue while using async_scan helper.  any updates?
