### ISSUE TITLE
UnsupportedProductError with AWS ES

### ISSUE THREAD

**Issue by caborabo** [elastic/elasticsearch-py#1687] opened 2021-08-19 02:21 UTC
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):  7.10.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.14.0

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:  Opening connection with elasticsearch-py 7.14.0 to AWS ES service running Elasticsearch 7.10.2 leads to "UnsupportedProductError".  No error against same AWS-ES host when running elasticsearch-py 7.13.3 (IAM credentials are validated).  Calling from ecs docker instance to AWS ES.  No difference if called using es-pandas -> elasticsearch-py or elasticsearch-py directly.  Used requests.get and verified AWS ES returns the correct info.

**Steps to reproduce**: Create AWS ES service instance with latest Elasticsearch version.  Run docker image in ecs that opens a connection to AWS ES.  

Code snippet of call that returns error:
>            region = CFG.D['AWS']['es']['Region']
>            host = CFG.D['AWS']['es']['Host']
>            credentials = boto3.Session().get_credentials()
>            awsauth = AWS4Auth(credentials.access_key, credentials.secret_key, region, 'es',
>                              session_token=credentials.token)
>            print('.  ES-Pandas: Connecting to {0}...'.format(host[-20:]))
>
>            r = requests.get(f"https://{host}", auth=awsauth)
>            print(r.text)
>            print(r.headers)
>
>            try:
>                esp = es_pandas(
>                    hosts=[{'host': host, 'port': 443}],
>                    use_ssl=True, verify_certs=False, ssl_show_warn=False,
>                    http_auth=awsauth, http_compress=True,
>                    timeout=30, max_retries=4, retry_on_timeout=True,
>                    connection_class=RequestsHttpConnection)
>

Output:
> csiLinkData            | .  ES-Pandas: Connecting to t-1.es.amazonaws.com...
> csiLinkData            | {
> csiLinkData            |   "name" : "12345678901234567890123456",
> csiLinkData            |   "cluster_name" : "037373737373:abc-def-x",
> csiLinkData            |   "cluster_uuid" : "-a7UBXXXXXXXXXXX7VrfA",
> csiLinkData            |   "version" : {
> csiLinkData            |     "number" : "7.10.2",
> csiLinkData            |     "build_flavor" : "oss",
> csiLinkData            |     "build_type" : "tar",
> csiLinkData            |     "build_hash" : "unknown",
> csiLinkData            |     "build_date" : "2021-05-21T20:25:46.519671Z",
> csiLinkData            |     "build_snapshot" : false,
> csiLinkData            |     "lucene_version" : "8.7.0",
> csiLinkData            |     "minimum_wire_compatibility_version" : "6.8.0",
> csiLinkData            |     "minimum_index_compatibility_version" : "6.0.0-beta1"
> csiLinkData            |   },
> csiLinkData            |   "tagline" : "You Know, for Search"
> csiLinkData            | }
> csiLinkData            | 
> csiLinkData            | Traceback (most recent call last):
> csiLinkData            |   File "/var/mvp/Common/upstream.py", line 492, in init_esp_if_needed
> csiLinkData            |     esp = es_pandas(
> csiLinkData            |   File "/var/mvp/packages/es_pandas/es_pandas.py", line 23, in __init__
> csiLinkData            |     self.es_version_str = self.es.info()['version']['number']
> csiLinkData            |   File "/var/mvp/packages/elasticsearch/client/utils.py", line 168, in _wrapped
> csiLinkData            |     return func(*args, params=params, headers=headers, **kwargs)
> csiLinkData            |   File "/var/mvp/packages/elasticsearch/client/__init__.py", line 294, in info
> csiLinkData            |     return self.transport.perform_request(
> csiLinkData            |   File "/var/mvp/packages/elasticsearch/transport.py", line 413, in perform_request
> csiLinkData            |     _ProductChecker.raise_error(self._verified_elasticsearch)
> csiLinkData            |   File "/var/mvp/packages/elasticsearch/transport.py", line 630, in raise_error
> csiLinkData            |     raise UnsupportedProductError(message)
> csiLinkData            | elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported > distribution of Elasticsearch

**Comment by pquentin** [comment] 2021-08-19 05:18
This is a duplicate of #1667

**Comment by sethmlarson** [comment] 2021-08-19 18:30
Closing this issue as duplicate of https://github.com/elastic/elasticsearch-py/issues/1667 and https://github.com/elastic/elasticsearch-py/issues/1666.

**Closed by sethmlarson** 2021-08-19 18:30 UTC
