### ISSUE TITLE
elasticsearch ConnectTimeoutError

### ISSUE THREAD

**Issue by LiangAllen** [elastic/elasticsearch-py#381] opened 2016-03-17 10:04 UTC
File "/application/python/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/application/python/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 84, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError((<urllib3.connection.HTTPConnection object at 0x7ff1c0f2fbd0>, 'Connection to xx.xx.xx.xx timed out. (connect timeout=10)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7ff1c0f2fbd0>, 'Connection to xx.xx.xx.xx timed out. (connect timeout=10)'))

elasticsearch==1.5.0
elasticsearch-dsl==0.0.11
urllib3==1.11

**Comment by HonzaKral** [comment] 2016-03-17 13:22
I am afraid I don't understand what the issue here is. This traceback means that there was a network timeout, it has nothing to do with the code or anything else and it is not a bug. I am closing this issue, feel free to reopen with more information, thanks!

**Closed by HonzaKral** 2016-03-17 13:22 UTC
