### ISSUE TITLE
Set the Content-Type header on requests

### ISSUE THREAD

**Issue by bgroff** [elastic/elasticsearch-py#445] opened 2016-09-05 23:11 UTC
Maybe I am misunderstanding the code, but it seems as if the actual http request (either urllib3 or requests) do no set the Content-Type. I would expect that at the very least, if the JSONSerializer was used that the Content-Type header would be set to "application/json" and something like "text/plain" if the payload is not JSON.

If my understanding is incorrect, then my apologies and feel free to close this ticket. If this is a valid concern and you are looking for a PR then I would be able to supply something in the coming weeks. 

As a side note, it looks like you have added support for arbitrary headers in the master branch, I think this could probably be used to set the Content-Type, but it seems to me like something more fundamental that you would always want set.

**Comment by HonzaKral** [comment] 2016-10-07 14:12
Can I ask you for the reasons behind this request? Elasticsearch itself assumes json by default and actually does it's own detection. There is no need for us to add a few bytes to every single request.

Not to mention that we cannot always guarantee what the body will contain since in some cases (user passing in a string as `body` parameter for example) we don't have control and in other cases (`bulk`, `mget`, `msearch`, ...) the body is not a valid json anyway.

Thank you!

**Comment by bgroff** [comment] 2016-10-13 22:04
Sure, we have a custom middleware that looks at the particular request and figures out if going directly to certain indices might be faster. We are using Django (and Django Rest Framework) which looks at the Content-Type to figure out which deserializer to use on the incoming request. The work around is not terrible, basically for each route just tell drf what to use.

I know it adds extra information to the http header, and figuring out the Content-Type is extra work. It also seems like using the headers method would allow us to set the Content-Type ourselves, it would just be nice to have the header set automatically if possible.

**Comment by HonzaKral** [comment] 2016-11-30 11:37
I am afraid that this is currently out of scope for the project. Since we cannot guarantee any of the content types we also cannot set the appropriate headers. Feel free to set them yourself globally using the `headers` parameter or on a per-request basis by extending the connection class and using your own.

**Closed by HonzaKral** 2016-11-30 11:37 UTC

**Comment by opentokix** [comment] 2017-08-23 07:52
When you run Elasticsearch 6.x it will not assume Json and throw error 406 instead. 

 (406, u'Content-Type header [] is not supported', {u'status': 406, u'error': u'Content-Type header [] is not supported'})

https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

"Starting from Elasticsearch 6.0, all REST requests that include a body must also provide the correct content-type for that body.

In earlier releases of Elasticsearch, the content-type was optional, and if it was missing or not recognised, then the server would sniff the content and make an educated guess regarding the content-type. That will no longer happen in Elasticsearch 6.0 - every incoming request needs to have the correct content-type for the body it contains.

This ability to enforce strict content-type checking has existed since Elasticsearch 5.3 via the http.content_type.required configuration setting. In 5.x it is optional, and defaults to false, in Elasticsearch 6.0, that setting defaults to true, and there is no way to disable it."

**Comment by HonzaKral** [comment] 2017-08-23 08:09
@opentokix this had been implemented in `5.2.0` by d862c8a.

For elasticsearch 6.x you wil have to use the master version of the elasticsearch-py library so it shouldn't be an issue.

**Comment by opentokix** [comment] 2017-08-23 08:10
Oh, awesome - I was running the package-provided library.

**Comment by WakeDown-M** [comment] 2018-01-30 08:59
Hello guys, could you please help me how to set that library to use master version? Where can I modify that requirements.txt file?

(Im now trying to learn how to use ES with Python to create some visualisations in Kibana so Im trying to import some data from online StarWars API :) ) IM getting transport error 406.

Thank you in advance!

**Comment by rjurney** [comment] 2018-02-03 12:41
I keep getting this error lately: pyelasticsearch.exceptions.ElasticHttpError: (406, 'Content-Type header [] is not supported')

Can this be fixed please?

**Comment by HonzaKral** [comment] 2018-02-05 14:50
@rjurney I am sorry but I cannot help you there, it is a different library, please open an issue there or migrate your code to use `elasticsearch-py` instead. `pyelasticsearch` hasn't been maintained for years and it is definitely not recommended for use.

**Comment by AdarshaG** [comment] 2018-02-25 10:55
@HonzaKral .. i tried installing elasticsearch-py, but get below error..

>  Could not find a version that satisfies the requirement elasticsearch-py (from versions: )
> No matching distribution found for elasticsearch-py

**Comment by yami14** [comment] 2018-04-03 06:41
@AdarshaG  .. were you able to solve this error , even I am facing the same issue. 
TransportError(406, 'Content-Type header [] is not supported')
and when I am trying to install elasticsearch-py instead. pyelasticsearch , it gives me same error. 
_**_**"Could not find a version that satisfies the requirement elasticsearch-py (from versions: )
No matching distribution found for elasticsearch-py"**_**_

**Comment by HonzaKral** [comment] 2018-04-03 07:58
`elasticsearch-py` is a name of the project, to install it just use `pip install elasticsearch`

**Comment by yami14** [comment] 2018-04-03 08:19
@HonzaKral  I have already installed pip install elasticsearch. But still getting this 
**TransportError(406, 'Content-Type header [] is not supported')** error.

Not Sure why it is not allowing me to create index.

**Comment by HonzaKral** [comment] 2018-04-03 08:21
and what version of `elasticsearch` did you install? Can yo try upgrading via `pip install -U elasticsearch`? Thanks!

**Comment by yami14** [comment] 2018-04-03 09:47
@HonzaKral I am using elasticsearch 2.0 , and when I am trying to upgrade the version it show below logs: 


(base) C:\Users\212627424>pip install -U elasticsearch
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577DF17860>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/elasticsearch/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577D0A6E80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/elasticsearch/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577D0A6C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/elasticsearch/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577DEF90F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/elasticsearch/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577DEF9FD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/elasticsearch/
Requirement already up-to-date: elasticsearch in c:\users\212627424\documents\python\lib\site-packages
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577DF36CF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/urllib3/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577DF36390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/urllib3/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577DF36748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/urllib3/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577DF36278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/urllib3/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002577DF17240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/urllib3/
Requirement already up-to-date: urllib3<2.0,>=1.8 in c:\users\212627424\documents\python\lib\site-packages (from elasticsearch)
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by HonzaKral** [comment] 2018-04-03 11:07
@yami14 this is a problem with your `pip` configuration where it cannot reach the PyPI index. Either way I am sorry, but we cannot help you there. The problem is outside of this library.

**Comment by chuttipayan** [comment] 2018-04-10 12:33
i downgraded the python library to 6.0.0 and then it worked

**Comment by wincle** [comment] 2018-06-05 12:30
in  lib/python2.7/site-packages/pyelasticsearch/client.py line:271
change _,prepped_response = ...
to prepped_response = ...
solve the problem
