### ISSUE TITLE
JSON serialization error with aggregation query

### ISSUE THREAD

**Issue by osallou** [elastic/elasticsearch-py#277] opened 2015-09-29 09:40 UTC
hi,
I face a serialization error when using aggregation. Here is the json result of my query

    {"took":3,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"toxsign","_type":"signature","_id":"560a38bf2e71a81fb95bccfb_1414e60a-a2bb-40ce-959e-7e67b4eaff92_48dae30e-3524-4a3e-8185-2486ebf35b95","_score":1.0,"_source":{"submission_date": 1443503263, "status": "private", "confidence": "", "last_updated": 1443503263, "description": "data1", "contributors": "osallou", "title": "test2", "treatments": [{"title": "treat2", "signatures": [{"genomic": [{"tissue": "genomic1", "id": "08cde85f827848e0a3f7a997a4c5db1c"}], "physio": [{"tissue": "tissue1", "id": "4c62413a7232455c948a7ba723795527"}], "id": "48dae30e-3524-4a3e-8185-2486ebf35b95"}], "organism": "human", "description": "sample", "id": "1414e60a-a2bb-40ce-959e-7e67b4eaff92"}], "dataset": "560a38bf2e71a81fb95bccfb", "owner": "xxx"}{ "index" : { "_index" : "toxsign", "_type": "signature" , "_id" : "560a38bf2e71a81fb95bccfb_1414e60a-a2bb-40ce-959e-7e67b4eaff92_d8560884-9fa3-431f-9739-04228dc728cb" } }}]},"aggregations":{"organism":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"human","doc_count":1}]}}}

The error is at:

    "owner": "xxxx"}{ "index" : { "_index" : "toxsign", "_type": "signature" , "_id" : "560a38bf2e71a81fb95bccfb_1414e60a-a2bb-40ce-959e-7e67b4eaff92_d8560884-9fa3-431f-9739-04228dc728cb" } }

The {"index": ...} is appended right after my hit. If I remove it, JSON is correct.

elastic-py version: 1.7.0
elastic server: 1.4.5

The same query without aggregation is correct.

**Comment by HonzaKral** [comment] 2015-09-29 09:52
Hi, this is definitely a bug, but it looks like it's either in the network stack or in elasticsearch itself. Can you reproduce this? If so, could you turn on logging to see what's actually going on? It might be a potential thread-safety issue too, are you using any threading in your code?

Thanks!

**Comment by osallou** [comment] 2015-09-29 10:03
I can reproduce with a simple script, no thread.
Do you want I launch elastic search with debug activated?

    from elasticsearch import Elasticsearch
    es = Elasticsearch( ['localhost'])
    es_db = 'mydb'
    es.indices.create(index='mydb', ignore=400)
   
    page = es.search(
          index = es_db,
          search_type = 'query_then_fetch',
          size = 1000,
          body = {
             "query": {
                "match" : { 'contributors': 'me' }
            },
            "aggs": {
                  "organism": {
                      "terms": {
                        "field": "treatments.organism"
                      }
                  }
             }
     })
    print str(page)

**Comment by HonzaKral** [comment] 2015-09-29 10:08
I cannot replicate that using your code, could you please turn on logging and try again? Thanks

to turn on logging add this code at the beginning of your script:

    import logging
    logging.basicConfig(level=logging.DEBUG)

**Comment by osallou** [comment] 2015-09-29 10:12
here is log file attached

**Comment by osallou** [comment] 2015-09-29 11:30
Requesting directly elasticsearch via GET API looks wrong too:

    curl -XGET 'http://localhost:9200/toxsign/signature/_search' -d '{
    "query" : {
        "term" : { "contributors" : "osallou" }
    },
    "aggs": {
              "organism": {
                  "terms": {
                     "field": "title"
                  }
              }
         }
    }
    '



    {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"toxsign","_type":"signature","_id":"560a38bf2e71a81fb95bccfb_1414e60a-a2bb-40ce-959e-7e67b4eaff92_48dae30e-3524-4a3e-8185-2486ebf35b95","_score":1.0,"_source":{"submission_date": 1443503263, "status": "private", "confidence": "", "last_updated": 1443503263, "description": "data1", "contributors": "osallou", "title": "test2", "treatments": [{"title": "treat2", "signatures": [{"genomic": [{"tissue": "genomic1", "id": "08cde85f827848e0a3f7a997a4c5db1c"}], "physio": [{"tissue": "tissue1", "id": "4c62413a7232455c948a7ba723795527"}], "id": "48dae30e-3524-4a3e-8185-2486ebf35b95"}], "organism": "human", "description": "sample", "id": "1414e60a-a2bb-40ce-959e-7e67b4eaff92"}], "dataset": "560a38bf2e71a81fb95bccfb", "owner": "xxx"}{ "index" : { "_index" : "toxsign", "_type": "signature" , "_id" : "560a38bf2e71a81fb95bccfb_1414e60a-a2bb-40ce-959e-7e67b4eaff92_d8560884-9fa3-431f-9739-04228dc728cb" } }}]},"aggregations":{"organism":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"test2","doc_count":1}]}}}


    "owner": "xxx"}{ "index" : {

so I should open bug directly in elasticsearch?

**Comment by HonzaKral** [comment] 2015-09-29 11:51
Yes this is is definitely a bug in elasticsearch. There is definitely something weird going on. It might be your environment, but either way it's wrong. Thank you for reporting this! I will close the issue here.

**Closed by HonzaKral** 2015-09-29 11:51 UTC
