### ISSUE TITLE
Memory leak in elasticsearch-py?

### ISSUE THREAD

**Issue by batlock666** [elastic/elasticsearch-py#212] opened 2015-03-30 12:02 UTC
I have created an index containing around 52,000 documents, each one containing data about a single person. I want to search for these persons by name. To see if my indexing- and searching-options are optimal, I devised a series of tests where I search for each person by name, and check which results I get back. These tests first used Mozilla's `elasticutils` library (which is built on top of `elasticsearch-py`). I found that the tests were using a lot of memory on the client side. Eventually the process started swapping, and I had to kill it. I replaced the `elasticutils` code with code that used `elasticsearch-py`, but I got the same memory problems. Finally I rewrote the tests so that they used the standard `httplib` and `json` libraries, and that seemed to solve the problem.

This table shows the memory usage (in kilobyte) for each version of my tests:

#searches | elasticutils | elasticsearch-py | httplib/json
--------------|--------------|------------------|-----------------
       0 |        37284 |         36548 |   36560
     500 |       316136 |        331344 |   37320
    1000 |       604160 |        631728 |   37336
    1500 |       880568 |        919912 |   37356
    2000 |      1163572 |       1223332 |   37356
    2500 |      1466908 |       1547208 |   37356
    3000 |      1773860 |       1863016 |   37356

This is the code I used to perform a search:

    from elasticsearch import Elasticsearch
    es = Elasticsearch([{"host": "localhost", "port": 9200}])
    results = es.search(index="myindex", body={...}, size=100)

I'm using `elasticsearch` v1.4.0 and Python v2.7.5.

Is there any option I have overlooked that can solve the memory problem, or is there indeed a memory leak?

**Comment by HonzaKral** [comment] 2015-03-30 12:04
Thanks for these tests, could you perhaps share the complete code you used for the various options?

**Comment by HonzaKral** [comment] 2015-03-30 12:34
I cannot seem to replicate this issue, using the following code I don't see the memory rise after initial few requests:

    from memory_profiler import profile
    from elasticsearch import Elasticsearch

    es = Elasticsearch()

    @profile
    def step(i):
        response = es.search(
            body={"query": {"filtered": {
                # make sure the body is always different, just in case
                "filter": {"bool": {"must_not": [{"term": {"_type": i}}]}},
                # make sure response is always different too
                "query": {"function_score": {"random_score": {}}}
            }}},
            size=1000
        )
        print(i, len(repr(response)))

    for i in range(10000):
        step(i)

tested on python 2.7.6 and 3.3.2

**Comment by batlock666** [comment] 2015-03-30 14:05
These are the fields used in the queries (there are a lot of other fields, but they're not used in the queries. They consist of strings, or lists of strings.):

* `person_types`: list of strings
* `name`: string, value is value of `preferred_first_name` + space + value of `preferred_last_name`
* `first_name`: list of strings
* `last_name`: list of strings
* `preferred_first_name`: string, value is also in `first_name`
* `preferred_last_name`: string, value is also in `last_name`

I define a custom analyzer `person_name`:

    {
        "char_filter": {
            "remove_spaces": {
                "type": "mapping",
                "mappings": "\\u0020=>",
            }
        },
        "analyzer": {
            "person_name": {
                "type": "custom",
                "tokenizer": "standard",
                "char_filter": ["remove_spaces"],
                "filter": ["standard", "asciifolding", "lowercase"],
            },
        },
    }

This is (part of) the mapping:

    {
        "people": {
            "properties": {
                "first_name": {
                    "type": "string",
                    "analyzer": "person_name",
                },
                "last_name": {
                    "type": "string",
                    "analyzer": "person_name",
                },
                "person_types": {
                    "type": "string",
                    "index": "not_analyzed",
                },
                "preferred_first_name": {
                    "type": "string",
                    "analyzer": "person_name",
                },
                "preferred_last_name": {
                    "type": "string",
                    "analyzer": "person_name",
                },
            }
        }
    }

This is the query I use:

    {'query': {'filtered': {
        'filter': {'bool': {'must': [
            {'terms': {'person_types': (
                'A', 'B', 'C', 'D')}}]}},
        'query': {'bool': {'must': [
            {'bool': {'should': [
                {'match': {'name': {
                    'fuzziness': 2,
                    'operator': 'and',
                    'query': SEARCHNAME}}},
                {'match': {'last_name': {
                    'fuzziness': 2,
                    'query': SEARCHNAME}}}]}}]}}}}}

Replace `SEARCHNAME` with the name you want to search for.

(The nested boolean filters/queries are generated by a series of functions that transform a set of incoming search parameters into this query.)

I use the following piece of code to measure the memory the process uses:

    import resource
    print "memory usage: %s" % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

I don't know if this is the correct way to measure memory usage, but it tells me the same thing as `top`: the process keeps using more and more memory, until it starts swapping.

I have conducted the following tests:

* `SEARCHNAME` = value of `preferred_first_name` + space + value of `preferred_last_name`
* `SEARCHNAME` = value `preferred_last_name` + space + value of `preferred_first_name`
* `SEARCHNAME` = value of `preferred_last_name`

Especially the last test uses a lot of memory.

**Comment by HonzaKral** [comment] 2015-03-31 09:58
Analyzers, or queries, have absolutely no impact on the python client - it treats them all as just json so this shouldn't affect anything. The only reason for different memory consumption I can think of would be if the number of results differed.

There is also an issue with how you measured the memory - `resource.getrusage(resource.RUSAGE_SELF).ru_maxrss` only means how much ram the python process has allocated, not how much it's using - in my example it keeps climbing ever so slightly all the time despite the memory reported by the profile remaining the same. If the OS ever needed to reclaim that memory, it should be able to do so.

It is still curious as to why this is so different for you compared to the raw approach, could you please share the python code you are using? The elasticsearch configuration is not relevant for this.

Thank you

**Comment by batlock666** [comment] 2015-04-01 11:10
Here it is:

    import csv
    import datetime
    import resource

    from elasticsearch import Elasticsearch


    class Timer(object):

        def __init__(self):
            self._start = None
            self._stop = None

        def start(self):
            self._start = datetime.datetime.now()

        def stop(self):
            self._stop = datetime.datetime.now()

        def delta(self):
            return self._stop - self._start


    class Counter(object):

        def __init__(self, initial=0):
            self._total = initial

        def increase(self, amount=1):
            self._total += amount

        def total(self):
            return self._total


    def report(counter=None, timer=None):
        if counter:
            print "total: %s" % counter.total()

        if timer:
            print "time: %s" % timer.delta().seconds


    class BaseRelevance(object):

        def __init__(self, in_name, out_name):
            self._in_name = in_name
            self._out_name = out_name

        def name(self, **kwargs):
            raise NotImplementedError

        def __call__(self):
            with open(self._in_name) as in_file,  \
                    open(self._out_name, "a") as out_file:

                reader = csv.reader(in_file)
                writer = csv.writer(out_file)

                counter = Counter()
                timer = Timer()
                timer.start()

                print "elasticsearch - memory usage %s" % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

                for row in reader:
                    identity, username, full_name, first_name, last_name, email = \
                        row
                    counter.increase()

                    name = self.name(
                        identity=identity,
                        username=username,
                        full_name=full_name.decode("utf-8"),
                        first_name=first_name.decode("utf-8"),
                        last_name=last_name.decode("utf-8"),
                        email=email,
                    )
                    query = {'query': {'filtered': {
                        'filter': {'bool': {'must': [
                            {'terms': {'person_types': (
                                'A',
                                'B',
                                'C',
                                'D')}}]}},
                        'query': {'bool': {'must': [
                            {'bool': {'should': [
                                {'match': {'name': {
                                    'fuzziness': 2,
                                    'operator': 'and',
                                    'query': name}}},
                                {'match': {'last_name': {
                                    'fuzziness': 2,
                                    'query': name}}}]}}]}}}}}
                    es = Elasticsearch([{"host": "localhost", "port": 9200}])
                    results = es.search(index="myindex", body=query, size=100)
                    results = results["hits"]["hits"]

                    found = len(results)
                    rank = 0
                    for result in results:
                        result = result["_source"]
                        rank += 1

                        if result["identity"] == identity:
                            writer.writerow([
                                identity,
                                full_name,
                                name.encode("utf-8"),
                                found,
                                rank,
                            ])
                            break
                    else:
                        writer.writerow([
                            identity,
                            full_name,
                            name.encode("utf-8"),
                            found,
                            0,
                        ])

                    if not (counter.total() % 100):
                        print "elasticsearch - processed %s" % counter.total()
                        print "elasticsearch - memory usage %s" % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

                timer.stop()
                report(counter=counter, timer=timer)


    class RelevanceFull(BaseRelevance):

        def name(self, full_name, **kwargs):
            return full_name

    relevance_full = RelevanceFull("names.csv", "relevance_full.csv")


    class RelevanceLast(BaseRelevance):

        def name(self, last_name, **kwargs):
            return last_name

    relevance_last = RelevanceLast("names.csv", "relevance_last.csv")


    class RelevanceLastFirst(BaseRelevance):

        def name(self, last_name, first_name, **kwargs):
            return last_name + " " + first_name

    relevance_last_first = RelevanceLastFirst("names.csv", "relevance_last_first.csv")

Tests are run by calling the callables `relevance_full()`, `relevance_last()`, or `relevance_last_first()`. These use a CSV-file named `names.csv` as input. Each row in this file has the following fields:

* identity
* username
* full_name
* first_name
* last_name
* email

The file has about 52,000 rows, and is about 4.0M.

**Comment by HonzaKral** [comment] 2015-04-01 11:19
The problem is you keep creating new instances of `Elasticsearch` - all the connections and everything. Expanding both your memory and hammering the server with new connection for every row.

Create one instance globally and reuse it, it should help.

**Comment by batlock666** [comment] 2015-04-01 13:13
Sorry, but moving the creation of `Elasticsearch`-instances out of the `for`-loop doesn't help. I still get the same issues. In an earlier version, the  `Elasticsearch`-instance was created outside the `for`-loop. I moved it inside the loop, hoping that it would trigger the garbage collector, freeing memory. Didn't help.

**Comment by HonzaKral** [comment] 2015-04-01 13:18
It definitely *must* be outside of the for loop, ideally completely outside of your code somewhere where a single instance is being created and then used throughout the code. Not only will it consume much less memory but also will be much faster since it will have only one connection open and keep reusing it.

I will look into the code in more detail to try and figure out what's going wrong.

**Comment by HonzaKral** [comment] 2015-04-01 14:53
I am sorry but I am still not seeing any leaks or any significant increase in memory consumption over time.

When I look at output of `ps` it agrees with the number presented by `memory_profiler` but the number reported by `resource.get_rusage` is higher (71 vs 60M). Could you perhaps try re-running your test with `memory_profiler.profile` decorater on your `__call__` method?

thanks!

**Comment by batlock666** [comment] 2015-04-02 08:09
I've added some code to limit the number of tests (lines 110-111). This is the result I got for 100 lines (some code where nothing happens memory-wise is removed):

    Line #    Mem usage    Increment   Line Contents
    ================================================
        92     36.2 MiB      0.0 MiB       @profile
        93                                 def __call__(self):
        94     36.3 MiB      0.0 MiB           with open(self._in_name) as in_file,  \
        95     36.3 MiB      0.0 MiB                   open(self._out_name, "a") as out_file:
        96

       ...

       105
       106     36.3 MiB      0.0 MiB               es = Elasticsearch([{"host": "localhost", "port": 9200}])
       107     94.9 MiB     58.6 MiB               for row in reader:
       108     94.9 MiB      0.0 MiB                   identity, username, full_name, first_name, last_name, email = row
       109     94.9 MiB      0.0 MiB                   counter.increase()
       110     94.9 MiB      0.0 MiB                   if counter.total() >= 100:
       111     94.9 MiB      0.0 MiB                       break
       112
       113     94.2 MiB     -0.7 MiB                   name = self.name(
       114     94.2 MiB      0.0 MiB                       identity=identity,
       115     94.2 MiB      0.0 MiB                       username=username,
       116     94.2 MiB      0.0 MiB                       full_name=full_name.decode("utf-8"),
       117     94.2 MiB      0.0 MiB                       first_name=first_name.decode("utf-8"),
       118     94.2 MiB      0.0 MiB                       last_name=last_name.decode("utf-8"),
       119     94.2 MiB      0.0 MiB                       email=email,
       120                                             )

       ...

       137     94.9 MiB      0.7 MiB                   results = es.search(index="phonebook", body=query, size=100)
       138     94.9 MiB      0.0 MiB                   results = results["hits"]["hits"]
       139
       140     94.9 MiB      0.0 MiB                   found = len(results)
       141     94.9 MiB      0.0 MiB                   rank = 0
       142     94.9 MiB      0.0 MiB                   for result in results:

       ...

       155                                             else:
       156     71.6 MiB    -23.3 MiB                       writer.writerow([
       157     71.6 MiB      0.0 MiB                           identity,
       158     71.6 MiB      0.0 MiB                           full_name,
       159     71.6 MiB      0.0 MiB                           name.encode("utf-8"),
       160     71.6 MiB      0.0 MiB                           found,
       161     71.6 MiB      0.0 MiB                           0,
       162                                                 ])
       163
       164     94.9 MiB     23.3 MiB                   print "elasticsearch - processed %s" % counter.total()
       165     94.9 MiB      0.0 MiB                   if not (counter.total() % 10):
       166     93.6 MiB     -1.3 MiB                       print "elasticsearch - memory usage %s" % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
       167
       168     94.9 MiB      1.3 MiB               timer.stop()
       169     94.9 MiB      0.0 MiB               report(counter=counter, timer=timer)

This is the result I got for 200 lines:

    Line #    Mem usage    Increment   Line Contents
    ================================================
       106     36.3 MiB      0.0 MiB               es = Elasticsearch([{"host": "localhost", "port": 9200}])
       107    155.4 MiB    119.1 MiB               for row in reader:
       108    155.4 MiB      0.0 MiB                   identity, username, full_name, first_name, last_name, email = row
       109    155.4 MiB      0.0 MiB                   counter.increase()
       110    155.4 MiB      0.0 MiB                   if counter.total() >= 200:
       111    155.4 MiB      0.0 MiB                       break

    ...

       155                                             else:
       156    140.9 MiB    -14.5 MiB                       writer.writerow([
       157    140.9 MiB      0.0 MiB                           identity,
       158    140.9 MiB      0.0 MiB                           full_name,
       159    140.9 MiB      0.0 MiB                           name.encode("utf-8"),
       160    140.9 MiB      0.0 MiB                           found,
       161    140.9 MiB      0.0 MiB                           0,
       162                                                 ])
       163                             
       164    155.4 MiB     14.5 MiB                   print "elasticsearch - processed %s" % counter.total()

And this is for 300 lines:

    Line #    Mem usage    Increment   Line Contents
    ================================================
       106     36.3 MiB      0.0 MiB               es = Elasticsearch([{"host": "localhost", "port": 9200}])
       107    205.0 MiB    168.7 MiB               for row in reader:
       108    205.0 MiB      0.0 MiB                   identity, username, full_name, first_name, last_name, email = row
       109    205.0 MiB      0.0 MiB                   counter.increase()
       110    205.0 MiB      0.0 MiB                   if counter.total() >= 300:
       111    205.0 MiB      0.0 MiB                       break

    ...

       155                                             else:
       156    141.0 MiB    -64.0 MiB                       writer.writerow([
       157    141.0 MiB      0.0 MiB                           identity,
       158    141.0 MiB      0.0 MiB                           full_name,
       159    141.0 MiB      0.0 MiB                           name.encode("utf-8"),
       160    141.0 MiB      0.0 MiB                           found,
       161    141.0 MiB      0.0 MiB                           0,
       162                                                 ])
       163                             
       164    205.0 MiB     64.0 MiB                   print "elasticsearch - processed %s" % counter.total()

**Comment by HonzaKral** [comment] 2015-04-02 09:09
This is weird - none of the lines that expand memory usage utilize elasticsearch at all. Since I cannot replicate it with elasticsearch or haven't had other reports from people using it, even to reindex their whole dataset, I need some replicatable  example.

Your script is much too complex and there are other factors that consume memory. Could you maybe trim it down and make a runnable example out of it so we can dig further?

Thank you for your patience, I am trying to resolve this issue, but it's challenging - memory leaks always are.

**Comment by batlock666** [comment] 2015-04-02 12:01
This is the minimal version:

    import csv

    from elasticsearch import Elasticsearch
    from memory_profiler import profile


    @profile
    def relevance(in_name, out_name):
        with open(in_name) as in_file, open(out_name, "w") as out_file:
            reader = csv.reader(in_file)
            writer = csv.writer(out_file)

            es = Elasticsearch([{"host": "localhost", "port": 9200}])

            for row in reader:
                identity, name = row
                name = name.decode("utf-8")

                query = {'query': {'filtered': {
                    'filter': {'bool': {'must': [
                        {'terms': {'person_types': (
                            'ugentEmployee',
                            'ugentSenior',
                            'ugentStudent',
                            'uzEmployee')}}]}},
                    'query': {'bool': {'must': [
                        {'bool': {'should': [
                            {'match': {'name': {
                                'fuzziness': 2,
                                'operator': 'and',
                                'query': name}}},
                            {'match': {'last_name': {
                                'fuzziness': 2,
                                'query': name}}}]}}]}}}}}
                results = es.search(index="phonebook", body=query, size=100)
                results = results["hits"]["hits"]

                found = len(results)
                rank = 0
                for result in results:
                    result = result["_source"]
                    rank += 1

                    if result["identity"] == identity:
                        writer.writerow([
                            identity,
                            name.encode("utf-8"),
                            found,
                            rank,
                        ])
                        break
                else:
                    writer.writerow([
                        identity,
                        name.encode("utf-8"),
                        found,
                        0,
                    ])

    if __name__ == "__main__":
        relevance("in.csv", "out.csv")

**Comment by HonzaKral** [comment] 2015-04-02 12:11
And what happens to the memory profile if you run the same code without the calls to elasticsearch (just replace the search with a static dictionary)?

**Comment by batlock666** [comment] 2015-04-02 12:20
Right now I'm kicking myself for not mentioning a crucial detail before: I was running my tests from within a Django shell, and not from the Python REPL.

This is the profiling I got from the script in my previous comment when I ran it in a Python REPL for 100 searches:

    Line #    Mem usage    Increment   Line Contents
    ================================================
        15     14.7 MiB      0.0 MiB           es = Elasticsearch([{"host": "localhost", "port": 9200}])
        16
        17     20.0 MiB      5.3 MiB           for row in reader:
        18     20.0 MiB      0.0 MiB               identity, name = row
        19     20.0 MiB      0.0 MiB               name = name.decode("utf-8")

And this is the result for the same script, but now from within a Django shell:

    Line #    Mem usage    Increment   Line Contents
    ================================================
        15     36.5 MiB      0.0 MiB           es = Elasticsearch([{"host": "localhost", "port": 9200}])
        16
        17     95.3 MiB     58.8 MiB           for row in reader:
        18     95.3 MiB      0.0 MiB               identity, name = row
        19     95.3 MiB      0.0 MiB               name = name.decode("utf-8")

There's a huge difference in the increment on line 17. Also, it ran a lot slower than when I ran it from Python.

Here's the result when I ran the script in the Python REPL for 300 searches:

    Line #    Mem usage    Increment   Line Contents
    ================================================
        15     14.7 MiB      0.0 MiB           es = Elasticsearch([{"host": "localhost", "port": 9200}])
        16
        17     20.1 MiB      5.4 MiB           for row in reader:
        18     20.1 MiB      0.0 MiB               identity, name = row
        19     20.1 MiB      0.0 MiB               name = name.decode("utf-8")

The increment on lin 17 is about the same as for 100 searches. And here is the result for the Django shell:

    Line #    Mem usage    Increment   Line Contents
    ================================================
        15     36.5 MiB      0.0 MiB           es = Elasticsearch([{"host": "localhost", "port": 9200}])
        16
        17    202.8 MiB    166.2 MiB           for row in reader:
        18    202.8 MiB      0.0 MiB               identity, name = row
        19    202.8 MiB      0.0 MiB               name = name.decode("utf-8")

In this case, the increment nearly tripled, from 58.8 to 166.2!

**Comment by HonzaKral** [comment] 2015-04-02 12:31
This is definitely weird. Could you unpack the body of the for loop - move into a separate function and wrap it with the `profile` decorator? That should give us an idea which part is eating the most.

**Comment by batlock666** [comment] 2015-04-02 12:52
I did what you asked, and got a lot of output. It looks like the only part that increases the memory is the call to `es.search()`, but not not every call does it. Here's a sample:

    Line #    Mem usage    Increment   Line Contents
    ================================================

        27     88.5 MiB      0.0 MiB                       'query': name}}}]}}]}}}}}
        28     88.5 MiB      0.0 MiB       results = es.search(index="myindex", body=query, size=100)

        27     88.5 MiB      0.0 MiB                       'query': name}}}]}}]}}}}}
        28     90.6 MiB      2.1 MiB       results = es.search(index="myindex", body=query, size=100)

        27     90.6 MiB      0.0 MiB                       'query': name}}}]}}]}}}}}
        28     91.3 MiB      0.7 MiB       results = es.search(index="myindex", body=query, size=100)

        27     91.3 MiB      0.0 MiB                       'query': name}}}]}}]}}}}}
        28     91.3 MiB      0.0 MiB       results = es.search(index="myindex", body=query, size=100)

        27     91.3 MiB      0.0 MiB                       'query': name}}}]}}]}}}}}
        28     91.9 MiB      0.7 MiB       results = es.search(index="myindex", body=query, size=100)

        27     91.9 MiB      0.0 MiB                       'query': name}}}]}}]}}}}}
        28     93.2 MiB      1.2 MiB       results = es.search(index="myindex", body=query, size=100)

        27     93.2 MiB      0.0 MiB                       'query': name}}}]}}]}}}}}
        28     94.5 MiB      1.4 MiB       results = es.search(index="myindex", body=query, size=100)

**Comment by HonzaKral** [comment] 2015-04-02 13:05
That's the same I am seeing in my tests and it makes sense - results need to be allocated, but this memory should be freed once results get garbage collected and I am indeed seeing that - at the end of the block the memory gos back down occasionally and overall it is stable.

**Comment by HonzaKral** [comment] 2015-04-06 13:45
Looking into it further with `tracemalloc` didn't reveal any other suspicious allocations or anything else.

I will close this ticket as it is not, at the moment, reproducible. Thanks for your patience, I am sorry I wasn't able to help.

**Closed by HonzaKral** 2015-04-06 13:45 UTC
