### ISSUE TITLE
Unclosed client session with FastAPI

### ISSUE THREAD

**Issue by blenzi** [elastic/elasticsearch-py#2349] opened 2023-10-27 16:30 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.17.3

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  (7, 17, 3)

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

Hi,

I have an API with routes across multiple python files. The module that uses and loads elasticsearch has this function:

```
@lru_cache
def get_elastic_search_client(hosts=elasticsearch_url):
    if not hosts:
        raise TypeError("ELASTICSEARCH_URL not defined")
    return AsyncElasticsearch(hosts=hosts)
```

That is used by many other modules. In `main.py`:

```
from es_utils import get_elastic_search_client
[...]
try:
    es_client = get_elastic_search_client()
except Exception:
    es_client = None

app = FastAPI(...)

@app.on_event("shutdown")
async def shutdown():
    if es_client is not None:
        await es_client.close()
```

following the recipe in https://elasticsearch-py.readthedocs.io/en/7.x/async.html#receiving-unclosed-client-session-connector-warning but I still get `Unclosed client session`. Any suggestions?

Thanks

**Comment by pquentin** [comment] 2023-10-31 11:09
Hello! I'm unable to reproduce your error.

Here's your code turned into a runnable FastAPI script:

```python3
import os
from functools import lru_cache

from fastapi import FastAPI

from elasticsearch import AsyncElasticsearch

ELASTICSEARCH_URL = os.environ["ELASTICSEARCH_URL"]


@lru_cache
def get_elastic_search_client(hosts=ELASTICSEARCH_URL):
    if not hosts:
        raise TypeError("ELASTICSEARCH_URL not defined")
    return AsyncElasticsearch(hosts=hosts)


es_client = get_elastic_search_client()
app = FastAPI()


@app.get("/")
async def main():
    return await es_client.info()


@app.on_event("shutdown")
async def shutdown():
    if es_client is not None:
        await es_client.close()
```

I only get an "Unclosed client session" if I comment out the close() function call. That said, I don't understand why you're using an LRU cache. If you have multiple clients, you need to close them all.

By the way, I know you reused what we documented, but note that a more modern way of doing this is using a Lifespan event: https://fastapi.tiangolo.com/advanced/events/

```python3
import os
from contextlib import asynccontextmanager

from fastapi import FastAPI

from elasticsearch import AsyncElasticsearch

ELASTICSEARCH_URL = os.environ["ELASTICSEARCH_URL"]
es_client = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global es_client
    es_client = AsyncElasticsearch(ELASTICSEARCH_URL)
    yield
    await es_client.close()


app = FastAPI(lifespan=lifespan)


@app.get("/")
async def main():
    return await es_client.info()
```

Closing as this is not an issue related to the Elasticsearch Python client, and the issue tracker is for confirmed issues or feature requests. Thank you.

**Closed** 2023-11-06 07:42 UTC
