### ISSUE TITLE
update() uses deprecated URL path

### ISSUE THREAD

**Issue by jaredmcqueen** [elastic/elasticsearch-py#1012] opened 2019-09-09 14:48 UTC
Elasticsearch wants users to update single documents using a different URL path:

```#! Deprecation: [types removal] Specifying types in document update requests is deprecated, use the endpoint /{index}/_update/{id} instead.```

When I update a single document using elasticsearch-py it looks like this:
`es.update(index=test123 id=3OjxjmwBw-PM1n_eu6f0, body={"doc":{"new_field":"blah}})`

The resulting path of that operation is:
`POST /test123/_doc/3OjxjmwBw-PM1n_eu6f0/_update`

The path needs to be changed to:
`POST /test123/_update/3OjxjmwBw-PM1n_eu6f0`

**Comment by viglia** [comment] 2019-11-29 15:30
Hi @jaredmcqueen ,

The client is using that deprecated endpoint to ease backward compatibility since users can still use types with 7.x.

This will be fixed in be fixed in 8.0.

If you are interested, you can find the APIs spec used for the client here https://github.com/elastic/elasticsearch/tree/7.1/rest-api-spec/src/main/resources/rest-api-spec/api

**Comment by viglia** [comment] 2019-12-10 15:34
Hi @jaredmcqueen 

Since I haven't heard from you and this is not a bug but an intended behaviour to  ease backward compatibility, I'm going to close the issue.

If this deprecation is affecting your work and you need to discuss this further feel free to reopen this ticket.

**Closed by viglia** 2019-12-10 15:34 UTC
Labels: question
