### ISSUE TITLE
Trace curl logging uses hardcoded path

### ISSUE THREAD

**Issue by msherry** [elastic/elasticsearch-py#489] opened 2016-11-11 22:57 UTC
It should use the value of `self.host` instead.

I have created a pull request which resolves this issue at https://github.com/elastic/elasticsearch-py/pull/488.

**Comment by HonzaKral** [comment] 2016-11-13 04:50
This is a duplicate of https://github.com/elastic/elasticsearch-py/issues/380

I will add some lines to the documentation to explain the reasoning behind the decision.

Thank you for the issue and the PR!

**Closed by HonzaKral** 2016-11-13 04:50 UTC
