### ISSUE TITLE
Index document with fields having null values

### ISSUE THREAD

**Issue by munotshubham** [elastic/elasticsearch-py#600] opened 2017-06-07 15:43 UTC
Hi,
I'm trying to index a document which has some fields with null values

```
es = Elasticsearch()
df = pd.read_csv('~/Documents/testserver-patients-22.csv')
for i in range(count):
   doc = {
        'PatientID': df.loc[i, 'PatientID'],
        'PaperChartNumber': df.loc[i, 'PaperChartNumber'] #This has some null vaues
        'PMRecordNumber': df.loc[i, 'PMRecordNumber'], #This has some null values
        'SubscriberID': df.loc[i, 'SubscriberID'],
        'PracticeID': df.loc[i, 'PracticeID'],
        'UserID': df.loc[i, 'UserID'],
        'FirstName': df.loc[i, 'FirstName'],
        'LastName': df.loc[i, 'LastName'],
   }
   res = es.index(index="patientdb-py", doc_type='db', id=i, body=doc)
```
This is the error I'm getting:
`
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse')`

**Comment by HonzaKral** [comment] 2017-06-14 13:55
Can you please provide more information? Standard `null` (or `None` in python) fields are supported but this looks like there is a conflict in your mappings - `failed to parse` signifies that one the of the field's type and value is mismatched.

To get more information, catch the exception and print its `.info` attribute.

Thank you!

**Comment by GlenRSmith** [comment] 2017-06-19 15:31
@munotshubham do you have more information here?

**Comment by munotshubham** [comment] 2017-06-19 16:14
So I couldn't exactly resolve the issue. So I tried filling up the null values in my dataset using 
`df.fillna("", inplace=True)`
and it worked fine after that.

**Comment by GlenRSmith** [comment] 2017-06-19 21:47
@munotshubham Thanks for the update. Closing. If you end up having additional problems, and can provide a direct reproduction (e.g. without the abstractions of invocations to functions in pandas), feel free to open a new issue.

**Closed by GlenRSmith** 2017-06-19 21:47 UTC
