### ISSUE TITLE
put_script wrong url

### ISSUE THREAD

**Issue by chiefelad** [elastic/elasticsearch-py#619] opened 2017-07-13 10:52 UTC
The implementation of put_script sends the request to /_scripts/<lang>/<id>, when it should send it to /_scripts/<id> according to ES documentation.

**Comment by HonzaKral** [comment] 2017-07-15 14:59
That shouldn't happen, the `lang` and `id` parameters are required and cannot be empty (actually `lang` shouldn't be required, sending a PR to fix it - https://github.com/elastic/elasticsearch/pull/25736 ).

Do you have a code to reproduce this issue? I cannot reproduce it myself, when I try that API everything works.

Thanks!

**Comment by GlenRSmith** [comment] 2017-10-11 20:47
@chiefelad Are you able to provide a reproduction of the reported issue?

**Comment by kradem** [comment] 2017-11-15 22:57
Hi everybody!

In the new 6.x package `lang` param is removed from `put_script` method.

In [ES 6 reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html) lang is still there. Also if I add a script without lang I get:

@elasticsearch-head
```
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "must specify lang for stored script"
}
],
"type": "illegal_argument_exception",
"reason": "must specify lang for stored script"
},
"status": 400
}
```
@elasticsearch-py
```
self = <Urllib3HttpConnection: http://localhost:9200>, status_code = 400
raw_data = '{"error":{"root_cause":[{"type":"parsing_exception","reason":"unexpected token [VALUE_STRING], expected [{, <source>]...parsing_exception","reason":"unexpected token [VALUE_STRING], expected [{, <source>]","line":1,"col":12},"status":400}'
```

**Comment by fxdgear** [comment] 2018-03-07 17:19
@chiefelad I'm gonna close this issue now. If you are still having problems in the future please feel free to reopen the issue with some additional data. Thanks

**Closed by fxdgear** 2018-03-07 17:19 UTC
